### ISSUE TITLE
Developer console

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#105]
Developers often need to see server side logging messages to debug the work they're doing, for example when writing email or web templates it is often necessary to see the server logs to figure out whats wrong.

But users must only be able to see logs for their own account. Logs should be displayed in a browser window in near real time

**Comment by Uafinder** [comment]
1. incorrect left menu highlighted. SHould be Logs instead of background tasks.
![image](https://cloud.githubusercontent.com/assets/1945230/5964109/2e2320ce-a7fa-11e4-8d0e-f2b529fd8d29.png)
2. There is a difference between INFO marks on already written log strings and new one, which appears when you are already watching the page.
![image](https://cloud.githubusercontent.com/assets/1945230/5964152/9a6e2ad0-a7fa-11e4-823b-1e86ca253758.png)

**Comment by bradmac** [comment]
Hey @tuzzmaniandevil would you mind finishing this off?

**Comment by tuzzmaniandevil** [comment]
1. - Fixed
2. - Fixed

**Comment by Uafinder** [comment]
Both fixed.
1. When implementing this on Prod, looks like online logging is not working. When you access this page - it shows you all log entries, but doesn't show new ones. (while i test this on QA it shows everything online and "follow" checkbox works properly).
