### ISSUE TITLE
Document for migration from jquery.forms-1.0.9 to jquery.forms-1.1.0

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1147]

**Comment by bradmac** [comment]
Its unlikely that anyone will actually migrate, because most kademi customers are agencies who only work on websites when they have a scope of work, and then they only fulfil that scope of work. They probably wouldnt do unnnecessary work like upgrading the forms plugin.

So really not a high priority at all.

**Comment by ducdhm** [comment]
@bradmac I think I'm done it with log messeage in code. The main think is we need generate doc for all jquery plugins.

**Comment by bradmac** [comment]
:+1:

**Comment by ducdhm** [comment]
Let's close this issue. When we have time, we will touch document of all jquery plugins.
