### ISSUE TITLE
Update snippets for EDM Editor

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1195]
Snippets list:
 * Image card with 100% image and description below
 * 2 cols with one is image and one is text 
 * 3 cols with all is image
 * Spacer (can config height)
 * Horizontal line (can config space to top and to bottom)
 * Unsubscribe link
 * Button (can config padding, background and border-radius)

FYI: Configurable feature will be completed in #1196

**Comment by bradmac** [comment]
Hey @ducdhm what do you think about this...
1. Keditor allows drag/drop of generic layout containers, eg 2 col, 3 col, etc
2. KEditor allows drag/drop of snippents **into** containers, for example drag/drop an unsubscribe snippet into the right column of a row

I guess we would need snippets to have inline editors, but not layout components. So that means we would really need 2 different types of snippets
 - layouts (eg 2 col, 3 col, gallery)
 - components (eg html sections, unsubscribe link, etc)

Thoughts .. ?

**Comment by ducdhm** [comment]
Have discussed with @bradmac, I'll implement new feature for https://github.com/Kademi/keditor (later)  and then apply into EDM Editor soon. For now, just update snippet.
