### ISSUE TITLE
Dragging the 'View online' link into an EDM template does not work

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1916]
View online link does no appear in the email when sent.  

http://admin.developer.olhub.com/groupEmails/177661859/#messages-tab

**Comment by ducdhm** [comment]
@bradmac The code snippet is still there but seem like dynamic component's content is not generated

**Comment by bradmac** [comment]
Works fine for me.

I've have this in the EDM (from drag/drop)
```
<section data-message="View in browser" data-type="component-viewEmailInBrowser"><div data-dynamic-href="/_components/edm/viewEmailInBrowser"></div>
</section>
```

And this is generated
```
<section data-type="component-viewEmailInBrowser" data-message="View in browser"><div data-dynamic-href="/_components/edm/viewEmailInBrowser"><a href="http://content.loopbackdns.com:8080/viewEmail?edmid=422&amp;miltonUserUrl=/users/d4&amp;miltonUserUrlHash=5833b9b6-7ac2-4627-9811-151bcb36bb71:L4vlPAu3jYPwqok6zuqlWw3zNlc">
            View in browser
    </a>

</div>
</section>
```

**Comment by ducdhm** [comment]
I still get empty dynamic element. Tested on my local and the link which Paddy provided

**Comment by bradmac** [comment]
I've had to comment out the additional call to DynamicComponentService. This is being done already by SimpleHtmlTemplater, so having it here means it will be called twice.

You should try to find out why its not being called. Note that if you use a bs320 site that does not use SimpleHtmlTemplater, so that would explain it. But we should only be developing on bs335+ sites now

**Comment by bradmac** [comment]
See line 159 in SimpleHtmlTemplater
