### ISSUE TITLE
Removing groups 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1977]
- I have a profile that has one membership in the admin group
- I had to remove the profile temporarily from the admin group whilst testing
- This removed the profile from the account i.e. it was no longer in the users page
- Removing a profile from an account when it has no groups seems very frustrating as I had to add the profile again

Thoughts....

**Comment by bradmac** [comment]
There should be validation telling you that if you remove the last group, that removes the profile. We did have this but was lost with the move to the top panel

**Comment by bradmac** [comment]
Current we give a warning message when deleting any membership that if it is the last they will lose access to the profile. However, users will tend to ignore this because its the same each time

Please update the message as follows:
- When deleting ask "Are you sure you want to remove this membership"
- IF it is the last membership, add an **additional** validation message "Warning: This is the last membership, deleting it will remove the profile from your account. Do you want to continue"?

**Comment by ducdhm** [comment]
Additional message:
![aaa](https://cloud.githubusercontent.com/assets/1289631/16110031/eee8c198-33d5-11e6-8d39-b71e145bae92.png)

**Comment by Uafinder** [comment]
Is it possible to place user to some kind of hidden group called "Deleted" or "Recycle" when removing last membership. This will make it easier to change group memberships and give a possibility to easily restore deleted account?

**Comment by bradmac** [comment]
No, we will in the future create a hard link between a profile and its owner organisation
