### ISSUE TITLE
Quick lead 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1979]
After I added a quick lead, I could not search on it to find it, instead I had to scroll for a while in the leads list to get to it.

Please add first name and surname fields to the popup dialogue.

![image](https://cloud.githubusercontent.com/assets/2201340/15920191/4f7e2780-2e5b-11e6-9de7-7d9fc5fd6732.png)

**Comment by bradmac** [comment]
We dont want to add text fields, because this is for when you dont want to entertext. 

But it should create a task to transcribe what has been captured, ie audio or photo

**Comment by bradmac** [comment]
Please create a task automatically to transcribe what has been captured

**Comment by mkhoudary** [comment]
@bradmac when I created a quick lead, a new lead was created and a task:
![image](https://user-images.githubusercontent.com/3704174/28248736-3fb8fc42-6a52-11e7-9cbc-60497f078164.png)
I think Paddy was talking about not being able to find the lead after adding it because there's no first name / last name, so we could redirect page after quick lead to the newly created lead.

What do you think?

**Comment by bradmac** [comment]
If its creating the task then thats fine, we dont need to do any more.
