### ISSUE TITLE
Make bs336 reward store templates content editor compatible

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2108]
Part of https://github.com/Kademi/kademi-dev/issues/2095

To do this we need to
1. Implement ComponentApplication on RewardStoreApp
2. Copy/paste the 2 component methods and the allComponents list from somewhere else (eg ReportingApp)
3. Edit the component details when added to the list
4. Create 3 component files for each component
5. Test in content editor by editing the template in the bs336 custom theme. Eg to edit page.html template
http://localhost:8080/repositories/bootstrap-theme/bootstrap336/website/theme/contenteditor?fileName=page.html

**Comment by anhnt** [comment]
@bradmac i've updated rewardstore templates to be compatible with content editor. 1 thing: its not rendered when view on the content editor like this `http://localhost:8080/repositories/bootstrap-theme/bootstrap336/website/theme/apps/rewardstore/contenteditor?fileName=rewardStoreDashboard.html` because there's no context for rewardstore app there. can you please advise?

**Comment by anhnt** [comment]
this is done now
