### ISSUE TITLE
Notes in the timeline

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2374]
http://clickstart-digital-crm.kademi.com.au/leads/22009517/

When a note is created and displayed on the timeline:

1) Give it the brown color like a Task
2) It should have a Pencil icon
3) The title should be 'Note Created' then the note description below

![image](https://cloud.githubusercontent.com/assets/2201340/18505048/b70172ba-7aa8-11e6-9437-805798fd1808.png)

**Comment by bradmac** [comment]
The icon cannot have the "brown" colour because that is the brand colour for "danger", and there is nothing dangerous about a note.

The default icon has been changed to a pencil. Note that the icon also depends on what action is selected, eg a phone call shows a phone icon, and an email action displays an envelope

The title also depends on the action, but the default has been changed to Note Created

**Comment by bradmac** [comment]
![screenshot-version1 kcrm loopbackdns com 8080 2016-09-15 11-12-56](https://cloud.githubusercontent.com/assets/826458/18533221/7909ada0-7b35-11e6-94f1-c5cf0a394239.png)

**Comment by bradmac** [comment]
Also adjusted widths and padding
