### ISSUE TITLE
Using profile uploader causes automation issue

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2406]
Manually creating a profile with a first name, surname and email then adding them to this group http://admin.cpaaustralia.kademi-beta.co/groups/RG-Retention-Outside-NSW/members/

Fires this triggers as intended http://admin.cpaaustralia.kademi-beta.co/autoEmails/40396503/

However uploading an Excel file matching on fields First Name, Surname, Email, Phone and Rgamount
[test.xlsx](https://github.com/Kademi/kademi-dev/files/485151/test.xlsx)

Intro the same group http://admin.cpaaustralia.kademi-beta.co/groups/RG-Retention-Outside-NSW/members/

Does not start the profile from the first email trigger, it skips it and starts them from this trigger http://admin.cpaaustralia.kademi-beta.co/autoEmails/40396558/

See this profile as an example: http://admin.cpaaustralia.kademi-beta.co/manageUsers/205582404/

**Comment by tuzzmaniandevil** [comment]
See this issue https://github.com/Kademi/kademi-dev/issues/2408
The event was being fired before the profile fields were populated.

**Comment by tuzzmaniandevil** [comment]
I've updated Beta with the fix @paddyow please test

**Comment by paddyow** [comment]
not fixed, still firing the 2nd trigger http://admin.cpaaustralia.kademi-beta.co/manageUsers/205582404/

**Comment by tuzzmaniandevil** [comment]
Uploaded another fix, I tested it and it's working. @paddyow please retest

**Comment by paddyow** [comment]
I uploaded this profile  http://admin.cpaaustralia.kademi-beta.co/manageUsers/206070210/#summary-tab

Tells me the email was sent but I did not receive any.
![image](https://cloud.githubusercontent.com/assets/2201340/18789317/eb40e76c-81ed-11e6-9c26-3de5aade00c0.png)

Nor did the email send appear in the email history http://admin.cpaaustralia.kademi-beta.co/emails/
![image](https://cloud.githubusercontent.com/assets/2201340/18789341/03ea3cfa-81ee-11e6-9352-9c509b7a56fb.png)

This is another profile I uploaded http://admin.cpaaustralia.kademi-beta.co/manageUsers/206070210/

Same thing, it says the email was fired but it was never received and did not appear in the email log.

**Comment by bradmac** [comment]
Just looked at this profile - http://admin.cpaaustralia.kademi-beta.co/manageUsers/206070210/#general-tab

It currently has email address - cpatesty@mailinator.com

One email has been sent to that profile - http://admin.cpaaustralia.kademi-beta.co/emails/206070218

Note that this email was sent to email address -  	testcpa_wes@mailinator.com

** The email address is different to the profile **

I assume you have changed the email address on the profile, right?

Note that the email WAS delivered successfully, which you can confirm from the email item page:
250 Ok , at 2016-09-23 09:33:37.021

The "250 Ok" is the response from the destination email server, so that is positive confirmation that it was delivered

**Comment by paddyow** [comment]
Looks good now!
