### ISSUE TITLE
Clicking on timer goal in profile page goes to template error page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2475]
http://kademi.admin.kademi.us/manageUsers/2483290/#funnelsTab-tab

![image](https://cloud.githubusercontent.com/assets/2201340/18981411/52623314-8721-11e6-8e4c-c2059858e069.png)

![image](https://cloud.githubusercontent.com/assets/2201340/18981417/5e2be438-8721-11e6-894a-8503cec57e46.png)

**Comment by bradmac** [comment]
@tuzzmaniandevil can you please create a management page for timers? This can be very simple, just needs to show summary stats for:
- number of timers currently queued
- number of timers due to fire in next 24 hours
- number of timers due to fire in next 7 days

And would be good to have a date histogram of timers due to fire. I think this information is available from the current app indexer

**Comment by tuzzmaniandevil** [comment]
Done, Moved Histogram to a separate issue https://github.com/Kademi/kademi-dev/issues/2482

**Comment by bradmac** [comment]
Please add a link from the timer settings panel in the funnel builder to its manage page
