### ISSUE TITLE
Lead page: Dont fill company informantion when select company

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2606]
http://hatton-crm.kademi.us/leads/3755906/
Company information
Search and select a company in company textbox. Must auto fill data to another textbox ( email, phone, address.. ).

**Comment by bradmac** [comment]
It might be better to display read only fields, and to allow editing through a popup modal

**Comment by hoanglinhlan** [comment]
data fill to textbox: passed
but when I click edit button to show popup, Popup display "loading ..." and dont show any textbox

**Comment by bradmac** [comment]
@ducdhm  a couple of things
- if there is no company, then you must not show the link to the company page
- the user must be able to create a company
- the user must be able to select a company
- the user must be able to edit company details (from a modal)
- do not display inputs as readonly, thats confusing to the user because they think they need to do something to make them editable. Just display the fields as text, ie do not use inputs at all

**Comment by bradmac** [comment]
@ducdhm as discussed, we need to finalise this, taking care to ensure good user experience

We need to make it easy for the user to enter a new company, or select an existing company.

Afterwards, they should be easily able to 
- edit details of the current company
- switch to a different company, ie link to a different existing company
- remove the company, so there is no linked company

**Comment by ducdhm** [comment]
Done!

**Comment by ducdhm** [comment]
New UI:

![aaaaaaaaaa](https://cloud.githubusercontent.com/assets/1289631/20127081/cc86e44e-a66d-11e6-851f-25b8b82fde67.png)

**Comment by hoanglinhlan** [comment]
local test
passed
