### ISSUE TITLE
Running ES query: Bad request when query is too long

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2764]
Looks like we limit the query length. got that error with query which has length 1852 including spaces

In this page http://localhost:8080/manageSearch/profile/

**Comment by bradmac** [comment]
@anhnt thats because the adhoc query page uses GET requests, and there is a limit to the querystring size

But you should not be using that page. Instead, save as a query, and then edit on the queries page - http://localhost:8080/queries/

The queries page uses POST instead of GET so doesnt have that length limitation

**Comment by bradmac** [comment]
BTW, the adhoc query page is going to be re-built with a visual editor, so there is no point updating it now
