### ISSUE TITLE
Admin login: Dont show any error message

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3171]
Profile https://lan-test.admin.kademi.com.au/manageUsers/46391155/#general-tab
Login to https://lan-test.admin.kademi.com.au

we dont show any error message if user loged in cases: 
- Profile has not permission to access admin page
- user input incorrect pass
- user input email that not existed

**Comment by bradmac** [comment]
@gonzalon please ensure that if a user is denied access to the admin they see an appropriate error message

**Comment by gonzalon** [comment]
@brad, For that user I'm seeing this:

![sin titulo](https://cloud.githubusercontent.com/assets/2773216/25823526/bb2d9278-3412-11e7-9ed3-f152ab179db8.png)



Should I add the messages for the wrong user / wrong password?

**Comment by bradmac** [comment]
@gonzalon the current problem is because of the change to jquery.user.js for 2FA. All we need is an exception handler around the parse line 192.

BUT we should not ever change static assets, because this can affect client sites using those assets.

So please do the following
- revert your changes to jquery.user.js, to exactly as it was prior to the 2FA issue
- create a new version of jquery.user-1.0.2.js and apply your 2FA changes there, ie to 1.0.3
- add an exception handler around JSON.parse
- integrate your new version, 1.0.3, into the theme, ie in admin2/normal.html, so it gets used in the admin site

**Comment by gonzalon** [comment]
@hoanglinhlan now is showing the same error message for the wrong password / wrong user name. couldnt reproduce the other one. see the screen below.

**Comment by hoanglinhlan** [comment]
passed
