### ISSUE TITLE
Theme dependencies

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3301]
Created a file `/apps/leadman-theme/dependencies.json` with content
```
{
    "appDependencies": [
        {
            "appId": "bootstrap",
            "branch": "bootstrap-3.3.6.4"
        }
    ]
}
```
so leadman-theme is depended on bootstrap theme and...
 * Expect: leadman-theme will be inherited everything from bootstrap theme.
 * Actucal: everything in leadman-theme will be overried from bootstrap theme. Example: `masterTemplate.html`

@bradmac: is it correct behavior?

**Comment by bradmac** [comment]
OK, so the issue we have here is that there is no ordering of dependencies.

Dependencies control which repos are enabled, but once they are enabled they are all at the same level, there is no overriding logic.

Its possible we could build a dependency tree and then look for resources in that order. But there is the potential for that to be inefficient.

The other option would be to arrange themes so that there is no overriding, instead the theme just provides additional resources to make a complete theme

**Comment by ducdhm** [comment]
```
Its possible we could build a dependency tree and then look for resources in that order. But there is the potential for that to be inefficient.
```
It feels like complicated with me. But seem like workable then. So something like: Depended app will override its dependencies resource

```
The other option would be to arrange themes so that there is no overriding, instead the theme just provides additional resources to make a complete theme
```
IMHO, It's easy solution but how about common file like masterTemplate.html? Leadman and polo have different masterTemplate than bootstrap theme

**Comment by bradmac** [comment]
> how about common file like masterTemplate.html? Leadman and polo have different masterTemplate than bootstrap theme

We would have a base lib called "bootstrap-base" which did not have any common files. Then "bootstrap-theme" would depend on bootstrap-base, and so would leadman and polo themes.
