### ISSUE TITLE
Table Uploader: Make it re-usable

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#3347]
All apps should use a standard framework instead of re-writing the code every time. This will also allow custom apps to make use of the framework.

**Comment by tuzzmaniandevil** [comment]
Some features that still need to be added, Either in this issue or part 2:
- Validators - An App needs a way to specify which fields are required, e.g.
  - Points Uploader
    - Either the Default Reward or the Reward Name fields are required
    - The "Awarded To" field is Required
  - Users Upload
    - Either a default group or the Group column needs to be specified
- Custom Fields need to support more fields types besides a list e.g.
  - text input - e.g. date format
  - checkbox
  - radio selector
- Move more uploaders over to the new framework
- Implementation for Custom Apps

**Comment by bradmac** [comment]
> Validators - An App needs a way to specify which fields are required, e.g. 
I think this should be part of the logic of the implementation of TableProcessor returned by the app. I would not necessarily expect to have apps return a particular instance, eg StandardTableProcessor.

> Custom Fields need to support more fields types besides a list e.g. 
I dont think there should be any data type representing custom fields. Instead an app should simply provide a template which generates the UI, and the inputs submitted from the form are made available to the app's table processor as attributes in a map. Otherwise you'll end up building a whole forms framework.

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan Please test all the new repoirts under /tableUploaders
