### ISSUE TITLE
Unable to control timer goal in KCRM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3431]
http://kcrm.kademi.us/leads/12822375/

![image](https://user-images.githubusercontent.com/2201340/27325226-1240c662-55eb-11e7-9aa2-75c1ff8caa3c.png)

It is displaying the task panel but there is no task. There should be control to control the timer.

**Comment by mkhoudary** [comment]
I think Brad removed the controls on purpose, because he wants others to use test accelerators with timers.. 

The use case you are talking about is a bit different, we usually create a task for this and use its timeout.. 

E.g. if I want to wait for the lead to respond for 10 days, I create a Task node, and put the reminder email as an outcome for the timeout connector of the task node.. Instead of using Timers.. Timers can only be used when you want to do something after a certain time without expecting anything.

So does this make sense? or we shall get back the controls?

**Comment by mkhoudary** [comment]
Paddy responded that we shall grant users a level of control over timers, since users may not use our JB our way.

**Comment by mkhoudary** [comment]
Done.. can be tested in QA server..

**Comment by bradmac** [comment]
@mkhoudary thats not quite right. We want to control all timed goals, not just timers

Thats why the original logic was "if not task" rather then "is timer"

So the original logic is correct, we just need to understand why it didnt work for timers

**Comment by mkhoudary** [comment]
It didn't work because in velocity it is **#if( $!page.currentTaskIsGoal )** and there's no such method in Java.. But there is a method in Java named currentGoalIsTask so I will use that and negate the condition in Velocity..

**Comment by mkhoudary** [comment]
Done..
