### ISSUE TITLE
Leads page: inline editing isnt working

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3477]
The editing fields no longer seem to work

![image](https://user-images.githubusercontent.com/826458/27566822-b05a3766-5b3b-11e7-93a3-217f347d1d76.png)

**Comment by anhnt** [comment]
worked for me with latest leadman-lib 1.3.7

**Comment by Uafinder** [comment]
The same for me, field disappears before i can edit something

http://vlad10-kcrm.kademi-ci.co/leads/?query=&leadType=active
http://vlad-test10.admin.kademi-ci.co/websites/vlad10-kcrm/version1/#panel_apps-tab
adminqa@mailinator.com

I've wrote a video
https://drive.google.com/file/d/0B9V2ZH-h_cR2V2V2cmRTNzJUXzg/view?usp=sharing

**Comment by anhnt** [comment]
http://vlad10-kcrm.kademi-ci.co/leads/?query=&leadType=active

@bradmac i fixed the problem that field editor disappear. but i can see other problem. after submit inline form edit, the table just reload but field is not updated. but wait some moment then refresh table, field is updated. i think ES will take some time to update index so if we reload table immediately it wont get updated data

**Comment by bradmac** [comment]
hey @anhnt can we just not reload the table? ie use client side code to update the cell

**Comment by anhnt** [comment]
fixed

**Comment by Uafinder** [comment]
Nope, it's not working.
Editor for field not disappear so you could successfully enter the value, but it doesn't updating field value or it's not visible. It happens only with dropdown fields.
Also problem could be because of entering value specific. For example deal amount... you enter amount and should press Enter. When you select value from dropdown pressing Enter doesn't help.
http://vlad15-leads.kademi-ci.co/leads/?query=&leadType=active
http://vlad-test15.admin.kademi-ci.co/funnels/journey1/version1/#properties-tab
It's a fresh account

**Comment by anhnt** [comment]
Please rebuild QA and then update leadman-lib to version 1.3.9d and test it again

**Comment by anhnt** [comment]
i've updated QA to use latest leadman-lib

**Comment by Uafinder** [comment]
IT works finally!
