### ISSUE TITLE
Upload Points Issue

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3526]
This account http://kademitest.admin.kademi.us

I uploaded these users:
[Users.xlsx](https://github.com/Kademi/kademi-dev/files/1121766/Users.xlsx)

The first time it failed.  Instead I had to re-index the account as it had none, then re-upload.  New accounts should not have to be indexed before they can be used.

I then uploaded these points 
[Points - May 2017-2.xlsx](https://github.com/Kademi/kademi-dev/files/1121769/Points.-.May.2017-2.xlsx)

The points were uploaded but I cannot see any transaction on the reward points page, or profile page.  The posting date is 15/06/17 01:00

![image](https://user-images.githubusercontent.com/2201340/27827147-3c4beb30-60f9-11e7-9ba7-47b7df163010.png)

**Comment by bradmac** [comment]
The points are not displaying because they have dates of 2000 years ago - 
![image](https://user-images.githubusercontent.com/826458/27850686-6016a6f2-61aa-11e7-9576-cf224b1d9ebd.png)

@tuzzmaniandevil please..
1. Ensure search index is updated when importing users
2. 2 digit years are handled correctly

**Comment by tuzzmaniandevil** [comment]
2. 2 digit years are handled correctly - **This is now handled with the new date stuff**
