### ISSUE TITLE
Test creating a new account and setting up a website with reward store

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3637]
**step 1**: from the admin dashboard click "create account". Enter name
**step 2**: confirm new account is created, and the user is logged in to the new account
**step 3**: click "create website" and enter a unique website name
**step 4**: go to manage apps page , and enable rewards and User Dashboard app
**step 5**: go to Apps tab in manage website page , and enable rewards and User Dashboard app
**step 6**: go to groups page , and add new group "member" , and add "Redeemer , ProductViewer " ruls to an organistion and select the org
**step 7**: go to  group access tab in manage website page , and add member and administrator group
**step 8**: go to  points buckets page , and create anew point system and enter unique name and save
and go to group tap in setting and add member and administrator group
**step 9**: go to products page , and add some products
**step 10**: go to reward store page , and create a new store (select website and points bucket) and save
from manage store page , add products

Then go to site , the product will appear in it
admin : http://alaa-reward.admin.kademi-prod.com
reward page : http://rewardstore001.kademi-prod.com/store001/
login with this user : http://alaa-reward.admin.kademi-prod.com/manageUsers/227531/#summary-tab

**Comment by AlaaKhalaf94** [comment]
Hi @bradmac 
This is a video that showing the entire process : https://youtu.be/R71-6bqZdfY
locally , because prod server is too slow

**Comment by bradmac** [comment]
Hi @AlaaKhalaf94, thats not the correct process. Please begin with "step 1"

** you must create a new account for this use case **

That is because we need to test a new client, and new clients always start with a new account.

Also, do not install apps individually from the apps page. Instead, just install "KRewardStore" from the marketplace

![image](https://user-images.githubusercontent.com/826458/28643182-1f3e4eb8-72a9-11e7-82a9-fc6c3f446535.png)

![image](https://user-images.githubusercontent.com/826458/28643212-3468863c-72a9-11e7-9ff6-2eca020a5d51.png)

![image](https://user-images.githubusercontent.com/826458/28643225-416ad2b8-72a9-11e7-8606-de1372da4b43.png)

![image](https://user-images.githubusercontent.com/826458/28643256-553af700-72a9-11e7-8100-d103423280df.png)

**Comment by AlaaKhalaf94** [comment]
Hi @bradmac
This is a video that showing the entire process : https://youtu.be/roBHqFNXg0E

I see , when I enable K-Reward Store app most of the above steps are done automatically
