### ISSUE TITLE
UserAdminRole can't edit user

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#3801]
Need to add the WRITE_ACL priviledge

> INFO  io.milton.http.HttpManager  - POST :: carters.admin.kademi.com.au///manageUsers/29670871/ start
> INFO  io.milton.cloud.server.web.KademiSecurityManager  - Authorisation declined for user: christine-jackson
> INFO  io.milton.cloud.server.web.KademiSecurityManager  - Required priviledge: WRITE_ACL was not found in assigned priviledge list of size: 4 for resource type=class io.milton.cloud.server.apps.admin.ManageUserPage href=/manageUsers/29670871/
> INFO  io.milton.cloud.server.web.KademiSecurityManager  - Found the following priviledges:
> INFO  io.milton.cloud.server.web.KademiSecurityManager  -  - UNLOCK
> INFO  io.milton.cloud.server.web.KademiSecurityManager  -  - READ
> INFO  io.milton.cloud.server.web.KademiSecurityManager  -  - WRITE_CONTENT
> INFO  io.milton.cloud.server.web.KademiSecurityManager  -  - READ_CONTENT

**Comment by Uafinder** [comment]
Yup, it gives me permission to edit profiles.
However some things about user admin role:
1. If you're sign in to admin console under user which has useradmin role, it's give an error with no permissions to access. That's because role has no access to dashboard.
2. If you go direct to manage users page, it work properly. However it gives some errors on other pages:
- unsubscribe page should be hidden
- Learning should be hidden too 
![image](https://user-images.githubusercontent.com/1945230/30700211-a25a34f2-9eef-11e7-91a0-4e49e8abb04b.png)
![image](https://user-images.githubusercontent.com/1945230/30700256-c26185f2-9eef-11e7-90b3-182532e8e4f0.png)

**Comment by bradmac** [comment]
"If you're sign in to admin console under user which has useradmin role, it's give an error with no permissions to access. That's because role has no access to dashboard." 
- Yes, this is expected. You should also grant the role AdminViewer

**Comment by bradmac** [comment]
"unsubscribe page should be hidden" 
- Actually, this should be considered part of user management, so should be visible

"Learning should be hidden too"
- Correct, should be hidden.

**Comment by bradmac** [comment]
I've added a check on whether the user can access elearning

**Comment by gonzalon** [comment]
I added another validations to not show other menu items

**Comment by Uafinder** [comment]
Yup, all looks fine, but unsubscribers page still shows no permission
![image](https://user-images.githubusercontent.com/1945230/34376606-3f858c44-eaf5-11e7-81d9-1b8fa07f3314.png)
http://vladtest12.admin.kademi-ci.co/unsubscribes/

**Comment by bradmac** [comment]
> Survey menu appears, should be hidden

Please ignore for now.

**Comment by Uafinder** [comment]
problem with ksurvey still appears, but closing this and move it to another issue with lower priority
