### ISSUE TITLE
Manage subs, plan table should show prices

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3834]
- show prices for paid plans
- remove Trial as an available option:

![image](https://user-images.githubusercontent.com/826458/30191342-5fc7abde-9494-11e7-91ce-555cdeb5909d.png)

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , How can I test ?

**Comment by gonzalon** [comment]
@AlaaKhalaf94 
1. First go to http://version56.kademi-www.kademi-ci.co/get-kademi.html and register 
![image](https://user-images.githubusercontent.com/2773216/31207838-22d30b20-a9dd-11e7-9773-ab05f556238d.png)
2. This would create a new account
3. Go to the license page
![image](https://user-images.githubusercontent.com/2773216/31207914-9e39fa58-a9dd-11e7-80f9-acfeb0420e6c.png)
4. Click on the "Manage Subscription" button
5. Login as the same user who created the account. !! (Be sure to double check this, because if not you are not going to see anything)
6. You are there :)

**Comment by AlaaKhalaf94** [comment]
Thanks @gonzalon 
passed
