### ISSUE TITLE
KCRM - double search result

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3901]
http://kcrm.kademi.us/leads/15248905/

When searching for a lead, I get two results.

1) Goes to the lead page
2) The other a page not found

Try searching for our Zoetis client, many results link to a 404 page.

![image](https://user-images.githubusercontent.com/2201340/30572511-6b909002-9d31-11e7-8032-001dc7e66be9.png)

**Comment by Uafinder** [comment]
Double search caused by search specific:
- first result is user profile, which is accessible without any problems;
- second result is lead profile, which is inaccessible and gives "Sorry, you don't have permission to view this page". This is because our logins are not part of group which are responsible for this lead;
So probably it's ok.

**Comment by bradmac** [comment]
yep, you need the sales role to access leads. So sounds good.
