### ISSUE TITLE
KCRM adding a new company requires re-index

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3966]
If I create a lead and add a new company, I have to re-index ORGs before I can load a 2nd lead using the same company.

I should not have to re-index each time I add a new company.

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/31079925-f0304998-a78f-11e7-81ec-d519a158badc.png)
![image](https://user-images.githubusercontent.com/1945230/31079938-f88ef15c-a78f-11e7-9803-cac51e99afd1.png)
![image](https://user-images.githubusercontent.com/1945230/31079964-0ca57206-a790-11e7-9551-3903f31cde6e.png)
After re-index
![image](https://user-images.githubusercontent.com/1945230/31080159-94e0c120-a790-11e7-8bf3-d1f1e0d7f822.png)

**Comment by bradmac** [comment]
Please provide a link to your site and admin account

**Comment by Uafinder** [comment]
Created a fresh account
http://vlad-test8.admin.kademi-ci.co
http://vlad8-kcrm.kademi-ci.co
adminqa@mailinator.com

1. I've created a lead, by entering all necessary data and provide company name as well
2. It does not appears in companies list http://vlad8-kcrm.kademi-ci.co/companies/
![image](https://user-images.githubusercontent.com/1945230/31127173-bef11f0c-a856-11e7-9400-873c784b7c9c.png)
3. It does not appears in companies field when create a next lead
![image](https://user-images.githubusercontent.com/1945230/31127830-a5860c1a-a858-11e7-9642-a09e6c0efff3.png)
However it exists in org list in admin
![image](https://user-images.githubusercontent.com/1945230/31127183-c937434c-a856-11e7-8396-f3c381e34d22.png)

**Comment by bradmac** [comment]
Hey @Uafinder, I've fixed but please note a couple of things...

I've updated some libs so please retest with a fresh account to get those updates.

Always install apps from the market place, dont enable directly on the apps tab of website manager. We will soon make an update to the apps page to prevent directly enabling.

The reason is that when installing from the marketplace the app automatically applies default configuration for lead groups and org types. Your site above was missing that config so wouldnt work anyway (although some fixes were needed)

**Comment by bradmac** [comment]
Note that dashboard alerts tell you what changes were made in app initialisation

![image](https://user-images.githubusercontent.com/826458/31154010-c4b68724-a900-11e7-88cf-6c590e4f7cc5.png)

And you can verify settings from leadman app settings form:
![image](https://user-images.githubusercontent.com/826458/31154048-efb415ae-a900-11e7-8d28-6fe55bce5e66.png)

**Comment by Uafinder** [comment]
Yeah, it works/
Thanks for detailed explanation
