### ISSUE TITLE
Timer Goal Bug

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4105]
http://moblix.admin.kademi-ci.co/funnels/redeemer-journey/version1/#journeyBuilder-tab

Timer Goal not firing.  Note the node connector is not aligned to the output.

![image](https://user-images.githubusercontent.com/2201340/31314194-dcbead90-ac45-11e7-9c35-4793abf442c8.png)

**Comment by mkhoudary** [comment]
@paddyow you are using the **past time** connector, this connector is used with relative time property in timers, so that if the node is entered while the timeout has already passed, we exit through past time, for regular timeout you shall use the timeout connector.

If that's clear with you we can reassign this issue to @ducdhm to check the misaligned line.

**Comment by paddyow** [comment]
OK just need to fix alignment of the connector.

**Comment by bradmac** [comment]
Looks ok to me:
![image](https://user-images.githubusercontent.com/826458/33696288-704e9026-db66-11e7-8d8b-fb03aac7948c.png)
