### ISSUE TITLE
Should ORG IDs allow spaces?

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4237]
http://kademi.admin.kademi.us/organisations/?q=Kademitest1%20test&searchOrgType=&parentOrgId=

If no, the ORG uploader needs fixing

![image](https://user-images.githubusercontent.com/2201340/31878627-77c3c47e-b826-11e7-8d9e-18a4bf755e02.png)

**Comment by bradmac** [comment]
I think if it does allow spaces then thats a good thing. Because Org ID's are intended to come from outside our system, that means we cant control what they'll be.

Eg if a customer uses a CRM where their customer account ID's have spaces ,we do want to be able to import them. I'm not sure if that will work everywhere, but thats a start

**Comment by bradmac** [comment]
Make sure you're using the import wizard, not the old CSV importer:

![image](https://user-images.githubusercontent.com/826458/31879419-dafa1cce-b839-11e7-9ed1-dd46dfd3c3e6.png)
