### ISSUE TITLE
Emoitcon Feedback not showing in email

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4276]
http://moblix.admin.kademi-ci.co/funnels/nurture-campaign/version1/emailAction-69b47d/#message-tab

![image](https://user-images.githubusercontent.com/2201340/32157861-3c6f3ca4-bd9a-11e7-890a-b9f37c3ca839.png)

However it is selected.

![image](https://user-images.githubusercontent.com/2201340/32157875-4e240042-bd9a-11e7-8246-7e9523461e41.png)

This is the landing page to start the journey http://version1.consumer-nurture-campaign.kademi-ci.co/

**Comment by ducdhm** [comment]
@bradmac Can you double-check with it? Seem like we can't find db. I tried:
 * `$applications.KongoDB.findDatabase()`
 * `$page.find("/jsondb").child()`
 * `$page.find('jsondb').child()` in KodeJS

None of them work

**Comment by bradmac** [comment]
@ducdhm the problem is just that KongoDB is not enabled in that website:
![image](https://user-images.githubusercontent.com/826458/32250185-600b2946-bef0-11e7-9369-1691938706fe.png)


kfeedbackapp doesnt have a dependencies.json file, so it currently doesnt have any dependencies, which is incorrect

Please create dependencies.json in kfeedbackapp and add a dependency on KongoDB, and anything else this app depends on

**Comment by anhnt** [comment]
Added KongoDB to kfeedback app dependencies
