### ISSUE TITLE
Image or video upload fails

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4329]
![image](https://user-images.githubusercontent.com/1945230/32441067-8264c882-c2fe-11e7-9339-f25ad25e4939.png)
When you try to upload image or video to poll details it fails:
1. When no folder is selected - upload finishes but nothing happens further
2. When folder repository for example selected - upload fails with Method not Implemented error
3. When folder polls selected - upload never finishes. 
http://vlad32-test.admin.kademi-ci.co/kpoll/managePolls/poll-SgrJqIhjwdWvICczPzQSvkidYNwEztMd#detail-tab

**Comment by bradmac** [comment]
@anhnt can you check this is using the new support for content uploads for custom apps? If there's a problem with that framework please assign back to me

**Comment by anhnt** [comment]
@bradmac i have added code to mount repo but there's no repo created

```
controllerMappings
                    .adminController()
                    .pathSegmentResolver('pollId', 'checkPollId')
                    .mountRepository("poll-content")
                    .enabled(true)

**Comment by tuzzmaniandevil** [comment]
Looks like the image and video uploader are uploading to `/` instead of the current href/dir so that's why it isn't uploading. The app repo only get's created when it get's used. So if the CKEditor isn't using the right directory it won't create the repo or upload to the correct place.

@ducdhm Can you see why the image and video addon for the CKEditor is using the wrong path?

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
It looks ok at the moment
