### ISSUE TITLE
Adding specific user to a specific group fails

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4366]
![image](https://user-images.githubusercontent.com/1945230/32609726-457fb202-c569-11e7-84dd-f112ee66b4bb.png)
![image](https://user-images.githubusercontent.com/1945230/32609776-6fe9773a-c569-11e7-81e8-291198ce4ed8.png)
I've tried both ways, but both failed - after pushing add it simple never ends.

http://vlad-test41.admin.kademi-ci.co/manageUsers/1882725/#summary-tab
try add "vouch" group

**Comment by gonzalon** [comment]
Just tested and its working but takes a loong time. For ex I added "vouch" and this is the delete time:

![image](https://user-images.githubusercontent.com/2773216/32703397-1d6dcc92-c85a-11e7-9715-2396f459656a.png)

**Comment by bradmac** [comment]
This is actually a performance issue, with same cause as 
https://github.com/Kademi/kademi-dev/issues/4357

**Comment by bradmac** [comment]
The problem is because the user being used is a sales person with many leads (100's or 1000's). Whenever the profile is updated, all leads the profile is the sales person for are re-indexed.

So this was taking a very long time.

However, i think we shouldnt do this, its an unnecessary performance overhead. It means whenever a sales person updates their phone number, name, etc, all of their leads need to be reindexed.

Instead, I've removed this so the leads for the sales person are not reindexed when the sales person profile is updated

This has reduced processing time to about 500ms

**Comment by Uafinder** [comment]
it works!
