### ISSUE TITLE
Changing a funnel name is problematic 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4422]
Currently there is no way to change the name of a funnel stage without reassigning all the leads again.  This is a problem if you have hundreds of leads but realize that the funnel stage needs to be updated to be more meaningful. 

Suggestion:
1) A funnel stage has an ID that does not change
2) There is a funnel name which can be changed but won't affect the leads in that stage
3) Funnel description 

![image](https://user-images.githubusercontent.com/2201340/32874143-77406806-cae4-11e7-94e1-d6f9f972200c.png)

**Comment by bradmac** [comment]
This means running an update on all leads in the funnel and reindexing them when a stage is changed

**Comment by bradmac** [comment]
Note that this should only apply to leads linked to this version of the funnel

**Comment by mkhoudary** [comment]
@bradmac I suggest that we don't allow changing stage name once created, we allow changing the label, because in many cases users reuse a stage by renaming it.. so updating all exiting leads would assume those are in the newly added stage which would be wrong.

Please note that stages are also used in journey nodes, so if you use a journey node with a stage named warm, then you changed it to warmm, the nodes will still be using warm and so will set the lead into an unexisting stage.

My suggestion is:
1- We don't allow renaming the stage, only changing the label.
2- When someone wants to replace a stage with another they simply should remove a stage and add another one, if it is a matter of giving another visual name then the label is enough.
3- When a stage is removed we shall update all leads to set the current stage to NULL for leads on the removed stage or ask the user to pick an alternative stage.

**Comment by bradmac** [comment]
Yep, sounds good.

But just one thing to note is that we allow leads to be connected to a specific branch of a funnel. So when we update leads it should only apply to those connected to the version of teh funnel being edited.

**Comment by mkhoudary** [comment]
Done..

@Uafinder to test this.. you will create a journey, have several leads at several stages, then go and delete the stage.. then check back the lead, you should see that the deleted stage is set to blank.

Also you shouldn't be able to modify stage name.. only the label after save.. before save you can do whatever.

**Comment by Uafinder** [comment]
Yeah, works like a charm!
