### ISSUE TITLE
Make org selector browser list size configurable

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4435]
The browse list is currently hard coded to a size of 20. Please make this limit configurable on the component:

![image](https://user-images.githubusercontent.com/826458/32920196-476743ee-cb8d-11e7-9d43-fae722fc20dd.png)

**Comment by bradmac** [comment]
Note:
http://cca.admin.kademi.com.au/repositories/reporting-lib/1.1.7/website/theme/apps/reporting/texteditor?fileName=browseOrgs.html
http://v1-updatelibs.cca-sales_cca.kademi.com.au/dashboard

**Comment by anhnt** [comment]
Done

**Comment by AlaaKhalaf94** [comment]
Hi Anh , here : http://fresh08-fresh08.kademi-ci.co//theme/contenteditor?fileName=defaultThemeTemplate.html I enable "Organisation selector" from setting

![capture1](https://user-images.githubusercontent.com/26510030/33932901-e3b8ede6-dffc-11e7-8186-0b3376afb846.PNG)


but in website , the org selector doesn't appear , appear white space instead of it

![capture2](https://user-images.githubusercontent.com/26510030/33932910-ea092aa8-dffc-11e7-8b75-1bede276337a.PNG)

Admin : http://fresh08.admin.kademi-ci.co/

**Comment by AlaaKhalaf94** [comment]
it need reindex to appear
