### ISSUE TITLE
kEditor failed to load on manage webpages

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4485]
![image](https://user-images.githubusercontent.com/1945230/33173184-d5c80222-d05b-11e7-9810-1d0de8023106.png)

http://vlad-test59.admin.kademi-ci.co/pages/vlad59-learn/version1/

**Comment by bradmac** [comment]
The initial problem was that the handlebars lib wasnt installed. I'm not sure why, it is correctly listed as a dependency of reporting-lib which was installed. I disabled reporting-lib and Reporting app, then enabled Reporting app and handlebars was installed correctly.

So lets keep an eye out for this, see if we can find out how that happened.

However, there is another error. The editor isnt initialising and its because keditor is using the wrong paths again:
http://version1.vlad59-learn_vlad-test59.kademi-ci.co/keditor/dist/css/keditor-0.0.0.min.css

I've checked that keditor 1.0.1 is installed

**Comment by bradmac** [comment]
@ducdhm can you please investigate the problem with keditor incorrect paths?

**Comment by ducdhm** [comment]
As discussed, path to `keditor` in `keditor-lib` should be `/theme/apps/keditor-libs/`

**Comment by ducdhm** [comment]
https://github.com/Kademi/kademi-dev/issues/4497

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Handlebars error again
![image](https://user-images.githubusercontent.com/1945230/33206221-2ba7b136-d112-11e7-8b58-0e0bab5760e2.png)
![image](https://user-images.githubusercontent.com/1945230/33206249-46a7be22-d112-11e7-8a01-e4ba2d17f9e6.png)
http://vlad-test60.admin.kademi-ci.co/websites/vlad60-repo/version1/#panel_apps-tab

**Comment by bradmac** [comment]
can you please check now?

**Comment by Uafinder** [comment]
Yup, it loading at the moment

**Comment by Uafinder** [comment]
Fresh account
![image](https://user-images.githubusercontent.com/1945230/34103304-fd72dd54-e3f4-11e7-916d-c1866dad7cc8.png)
http://vladtest08.admin.kademi-ci.co/pages/vlad08learning/version1/

**Comment by bradmac** [comment]
@ducdhm please have a look, and ping me if you need a hand

**Comment by anhnt** [comment]
handlebars-lib is not enabled that causes the error

**Comment by Uafinder** [comment]
fresh account
create one website - install leads app there, create another website, install learning app there. go to edit pages. go bac to the second website apps and enable reports
http://vladtest10a.admin.kademi-ci.co/websites/vlad10alearn/version1/#panel_apps-tab

**Comment by bradmac** [comment]
@anhnt please let me know if yuo need a hand with deps. Anything thats needed should be loaded automatically

**Comment by bradmac** [comment]
from Anh

> 
>  So on web1 you installed KLeadman app which will install handlebar-lib
> then on web2 install KLearning app
> then enable Reporting app
> handlebar-lib will not enable on web2

**Comment by bradmac** [comment]
@ducdhm can you please investigate?

**Comment by ducdhm** [comment]
@bradmac All dependencies are up-to-date. It's backend issue. Please check it

**Comment by bradmac** [comment]
Not a backend issue. 

The problem here is that the reporting app is being enabled from the apps page which is not valid. Anyone who does that also needs to manually install dependencies.

The real problem here is that Reporting is not available in the marketplace, so we should create a KReportingApp
