### ISSUE TITLE
Member Reporting Component - registration date and points balance are empty

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4511]
![image](https://user-images.githubusercontent.com/1945230/33317143-018e6784-d43f-11e7-9010-6b421b8e2cd8.png)
Date registration column is empty
http://version1.vlad62-repo2_vlad-test62.kademi-ci.co/reports.html
http://vlad-test62.admin.kademi-ci.co/pages/vlad62-repo2/version1/

Also points balance is empty
![image](https://user-images.githubusercontent.com/1945230/33317675-7c178e12-d440-11e7-8454-8e0056380093.png)
http://vlad-test62.admin.kademi-ci.co/

**Comment by anhnt** [comment]
To show points balance you need to enable KRewardstore app since we use API of that app to get user point balance

![image](https://user-images.githubusercontent.com/735555/33357437-a9898e72-d4f4-11e7-9d26-3ebc6bfdd7a3.png)

Then in component settings there will be selectbox to select points bucket to get points balance
![image](https://user-images.githubusercontent.com/735555/33357471-d9c25d58-d4f4-11e7-9070-b027c3651646.png)

I've pushed some fixes so please update user-lib to test on this current account

**Comment by Uafinder** [comment]
Registered date is showing ok

1. points balance still empty
![image](https://user-images.githubusercontent.com/1945230/33380095-a35e82fe-d522-11e7-8c8e-930d4f2bef1c.png)

2. When enabling RewardStore app (via enable app, not install feature) for Report Site it creates new reward store (e.g. point-reportingsite) which is not necessary.
![image](https://user-images.githubusercontent.com/1945230/33380187-edff5cd4-d522-11e7-9bd6-bd2cfe38f11c.png)

**Comment by bradmac** [comment]
> When enabling RewardStore app (via enable app, not install feature) for Report Site it creates new reward store (e.g. point-reportingsite) which is not necessary.

There is no code to auto-create reward stores in RewardStoreApp, only in the marketplace app.

**Comment by bradmac** [comment]
@Uafinder when testing i think you should always use the marketplace to install apps. We will actually remove the ability to enable apps from the apps page in the near future.

**Comment by anhnt** [comment]
> points balance still empty

Fixed, try to test that page again because i already applied the fix :)

**Comment by Uafinder** [comment]
Finally it's ok
