### ISSUE TITLE
Create Bootstrap tabs Component

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4768]
We need a component that enables creating  bootstrap tabs:
![image](https://user-images.githubusercontent.com/3704174/34819407-51c64344-f6c6-11e7-8aa2-0f231e4afec2.png)

Allowing us to assign a hyperlink or function to each tab on click, and allowing tabs to be highlighted when page opens using MVEL or any other relevant method.

Our target is to be able to implement this view:
![image](https://user-images.githubusercontent.com/3704174/34819472-7f7359f8-f6c6-11e7-8941-4a9ce5152829.png)

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-sudler-phhub/issues/8
https://github.com/Kademi/client-sudler-phhub/issues/9

**Comment by bradmac** [comment]
Urgh ... we've avoided tabs deliberately because it will be a hassle for visual editing.

A couple of options i can think of..
1. Enhance KEditor's support for containers so that instead of a container only being columns, it can also handle a tab structure. Best for content editing, but will be a bit of work
2. Have a tab component which just renders the tabs and acts as a navigation control with content underneath, and uses pjax to load content. So you would have 3 pages, each with the tab component. Harder for content editing, but easier to implement.
3. Do something like we do with the carousel, where content for each tab is edited from settings. But this is very limiting on the content creation.

**Comment by bradmac** [comment]
@ducdhm what are your thoughts?

**Comment by ducdhm** [comment]
@bradmac I think we can introduce container type. Instead of having only `container` as type of container. We can introduce more types of container same as component. Such as `container-grid`, `container-tab`, etc...

**Comment by bradmac** [comment]
:+1:

**Comment by ducdhm** [comment]
New container:
![newui2](https://user-images.githubusercontent.com/1289631/35427843-65fc9122-029e-11e8-846a-f6f3ef5023b1.png)

New settings only for tab container:
![newui](https://user-images.githubusercontent.com/1289631/35427855-7383421e-029e-11e8-9abe-5956d53b012b.png)
