### ISSUE TITLE
Journey email node / history not showing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4804]
http://kademi.admin.kademi.us/funnels/agency-campaign-1/version1/emailAction-8ea87b/#history-tab

1) Not showing any email history.  A list of 100 was sent out today.

2) Add extra field to show conversation status i.e. email was sent, opened or converted.  
Like this page http://kademi.admin.kademi.us/manageUsers/17712683/#emailAppTab-tab

3) Add export to CSV

![image](https://user-images.githubusercontent.com/2201340/35078754-c8cdc0c0-fc57-11e7-852c-22ad1ac9230c.png)

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/35104531-bee72816-fc71-11e7-955d-377e0e66765f.png)
Bugs on the image

Also, when you bring mouse cursor to the email row, it change form link it could be clickable, but it doesn't.
http://vladtest23.admin.kademi-ci.co/funnels/first-journey/version1/email1/#history-tab

**Comment by tuzzmaniandevil** [comment]
Fixed

**Comment by Uafinder** [comment]
yup, fine now
the only thing is retry looks like
![image](https://user-images.githubusercontent.com/1945230/35147793-9239793e-fd18-11e7-8843-bfec5dab70fd.png)
not sure if it's... if so, you could close the issue...

**Comment by bradmac** [comment]
Yep, worth looking into

**Comment by Uafinder** [comment]
Yup, and this one
![image](https://user-images.githubusercontent.com/1945230/35441917-0ce5f474-02ae-11e8-9953-f3a8d27e80c5.png)
1. Should be failed instead of undefined
2. Shouldn't be details for failed email sending.

**Comment by Uafinder** [comment]
Undefined, it because all statuses are not displaying correctly on this page
![image](https://user-images.githubusercontent.com/1945230/36030838-6500afba-0db1-11e8-8256-8528c4ad7c25.png)
For example here, undefined = retrying, in previous example undefined = failed
You could gain failed status by sending email to user adminqa@mailinator.com (have no idea why but it not sending email there)
Also you could gain retrying status by sending more than 50 emails to your kademi account (fast mail doesn't allow more than 50 emails in one minute from one sender)
http://vladtest31b.admin.kademi-ci.co/funnels/first-journey/version1/email1/#history-tab

**Comment by bradmac** [comment]
New UI:
![image](https://user-images.githubusercontent.com/826458/36080351-ad144368-0ff3-11e8-8fd5-0d9670918997.png)

**Comment by Uafinder** [comment]
Yup, looks good now
