### ISSUE TITLE
Registration form: phone number country code issue

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4911]
There is a user in waterco that cant register http://training.waterco.com/

![image](https://user-images.githubusercontent.com/2773216/35944071-226f8e24-0cc0-11e8-9490-979a32ef1fdf.png)

Tested with my NZ phone (+64.. ) didnt work either.

**Comment by ducdhm** [comment]
@bradmac As I checked in libphonenumber, It requires country phone code. As default,, I'll make it as AU. If user enters NZ phone number, it'll be false. Is it ok?

**Comment by bradmac** [comment]
I've tried it with valid country codes and that was rejected:

![image](https://user-images.githubusercontent.com/826458/36072017-0e12ca76-0f7d-11e8-9ba7-9eeeb13836d6.png)

And we cant make a default of AU because we have clients outside of australia.

So i think that if we cant make it work then we just disable phone number validation entirely.

If we can make it work then it would be nice to use the account organisation country as the default.

**Comment by ducdhm** [comment]
Fixed in waterco!

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/36104476-d729c502-101a-11e8-8b2d-3a9fe516427c.png)
Real number from my country
Also tried with number which Brad provided 64292009999
![image](https://user-images.githubusercontent.com/1945230/36104665-51e160c0-101b-11e8-8c13-1dd99acf9771.png)

**Comment by bradmac** [comment]
hey @ducdhm i think we should just completely disable phone validation. We dont have time to look into this, but we need regos to work.

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Looks good
