### ISSUE TITLE
Assets when uploading showing incorrect filename

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4920]
1. Open edit page
2. Add some image component
3. Upload image
4. Note that name will be weird
![image](https://user-images.githubusercontent.com/1945230/35962948-e10bf26e-0cbb-11e8-8ea4-c8bfc8cf07cf.png)
 http://vladtest31a.admin.kademi-ci.co/pages/vlad31aweb/version1/

**Comment by bradmac** [comment]
@ducdhm the asset is being created capturing the correct file name and a UID is being assigned. 

But it looks like you're adding an item to the asset list with the UID instead of the file name. The UID is needed internally, but users should just see the file name.

Eg this upload response
```
originalName | kang-and-kodos.jpg
length | 51822
href | /assets/77fec2ff-3d80-4f0e-b409-d1bd378d4fe4
contentType | image/jpeg
```

Displays this initially:
![image](https://user-images.githubusercontent.com/826458/36009541-6baa1f90-0db1-11e8-8ce4-af394208bd82.png)

But if i search i see the correct file name:
![image](https://user-images.githubusercontent.com/826458/36009549-7cff928e-0db1-11e8-8ec5-17c76c16f39e.png)

**Comment by bradmac** [comment]
Please update the script to display the user friendly file name and use the UID for internal identification

**Comment by Uafinder** [comment]
it works!
