### ISSUE TITLE
Create task journey node duplicating

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5005]
![image](https://user-images.githubusercontent.com/1945230/36383382-a5a13cb6-1594-11e8-80fb-cf9a4bae3b17.png)
there are two different nodes for task creation in journey builder
is it by design?

**Comment by bradmac** [comment]
Yes, its intentional

"Create Task" - is an action which creates a task and assigned and the journey immediately continues. The journey does not wait for the task to be completed. This can be followed by the "Task Complete" goal.
"Task" - is both an action and a goal. It creates and assigns the task, and it also waits for the task to be completed. So this is simpler to use, but less flexible.

**Comment by Uafinder** [comment]
Understood... thanks
