### ISSUE TITLE
New points leaderboard component for web

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5053]
should have option for selecting a points tag, which will show a leaderboard only for points of that type

**Comment by Uafinder** [comment]
Works perfect.
One thing:
When current user doesn't have any points in selected points tag, it shows current user with N/A rank
Is it expected behavior:
![image](https://user-images.githubusercontent.com/1945230/36895615-33964ce2-1e18-11e8-81ad-69424458e175.png)
http://vladtest38b.admin.kademi-ci.co

**Comment by bradmac** [comment]
yeah, probably should show their rank.

**Comment by Uafinder** [comment]
looks fine
