### ISSUE TITLE
Assets App Indexer needs re-indexing when assets change

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5055]
Currently when we add/modify/delete assets, the indexer isn't updated.. we now need this as work in PHHub is needing it

**Comment by bradmac** [comment]
:+1:

**Comment by mkhoudary** [comment]
Done..

**Comment by mkhoudary** [comment]
@Uafinder to test this you will need to create a site with assets, use an asset query to show them, then try to modify, delete, add and see if the assets update or not

**Comment by Uafinder** [comment]
so, still about this one
https://github.com/Kademi/kademi-dev/issues/5055
i've create a content type, add some fields there and a template
http://vladtest46.admin.kademi-ci.co/content-types/conttype/
then i've created some assets of this type
http://vladtest46.admin.kademi-ci.co/asset-manager/?q=category:conttype&type=conttype
then i created a query,but seems like something not good with it, because when i check it on frontend - it returns nothing.
http://vladtest46.admin.kademi-ci.co/asset-manager/5e0c5310-5a29-49e5-b408-4a25783a4908
this page
http://vladtest46.admin.kademi-ci.co/pages/vladtest46web/version1/?contenteditor=page5.html
so, still about this one
https://github.com/Kademi/kademi-dev/issues/5055
i've create a content type, add some fields there and a template
http://vladtest46.admin.kademi-ci.co/content-types/conttype/
then i've created some assets of this type
http://vladtest46.admin.kademi-ci.co/asset-manager/?q=category:conttype&type=conttype
then i created a query,but seems like something not good with it, because when i check it on frontend - it returns nothing.
http://vladtest46.admin.kademi-ci.co/asset-manager/5e0c5310-5a29-49e5-b408-4a25783a4908
this page
http://vladtest46.admin.kademi-ci.co/pages/vladtest46web/version1/?contenteditor=page5.html

And there is a side question - how can add link to the asset to the frontend?
