### ISSUE TITLE
Ktoolbar and less file broken

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5100]
http://kademi-www.admin.kademi.us/pages/kademi-www/version1/

I created a new account
Created a website
Ktoolbar options do not show
If you edit the less file and save, the updates do not show in the website
Unable to click on the profile dropdown button

![image](https://user-images.githubusercontent.com/2201340/37238996-d00fd7b8-2486-11e8-9ad5-9f5c5eada1a1.png)

**Comment by ducdhm** [comment]
New UI: Now KToolbar styles is not depend on theme
![newui](https://user-images.githubusercontent.com/1289631/37276271-d882b102-2613-11e8-8d47-6b4b0ea36779.png)

**Comment by bradmac** [comment]
The lib problems are fixed.

However there is a problem with order of loading:
```
ReferenceError: $ is not defined
```

jquery has positiion: 0 so should be loaded first. must be something wrong with building the munged path

**Comment by paddyow** [comment]
Note editing this less file http://kademi-www.admin.kademi.us/repositories/kademi-www/version1/website/theme/texteditor?fileName=theme-params.less

Does not update the website here http://version1.kademi-www_kademi-www.kademi.us/homepage.html

**Comment by bradmac** [comment]
OK, so one problem is that youre trying to set styles on tags instead of using parameters

Make sure you override params so they get factored into the theme. Easiest way to do this is to use the style editor:
![image](https://user-images.githubusercontent.com/826458/37333187-8d9ff38e-270d-11e8-9bbc-7fd448fc1547.png)
