### ISSUE TITLE
Leadman app doesn't work at all

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5141]
I've create a fresh account, create a website and install a leadman app there
Then I trying to open site from view website
It shows empty page without any errors
Then I've tried to change theme to leadman-theme, and this cause nothing changed.
http://vladtest42a.admin.kademi-ci.co/websites/

**Comment by anhnt** [comment]
This is because leadman-theme repo is empty. maybe the sync job was failed 
http://rootorg.admin.kademi-ci.co/repositories/leadman-theme/1.4.0/
http://vladtest42a.admin.kademi-ci.co/repositories/leadman-theme/1.4.0/

![image](https://user-images.githubusercontent.com/735555/37551222-62ee2692-29ce-11e8-99e8-befb732692ed.png)

**Comment by anhnt** [comment]
Synced and tested with fresh account working ok http://anhtest27.admin.kademi-ci.co/websites/l1/version1/#panel_apps-tab

**Comment by AlaaKhalaf94** [comment]
tested
