### ISSUE TITLE
New Claim App update

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5214]
Required workflow.

Claim workflow 1:

    Sales data gets loaded
    Participant sees a list of claims for their organization
    Participant can check multiple claims
    Participant clicks the 'claim' button and the claim(s) disappear from the list and get marked as 'claimed '
    Claimed sales can be found in a separate list
    When a claim is made, Kademi will use a journey to do something else i.e. award points which will include a formula to calculate the points
    Once a claim has been made, it cannot be reversed, but a point credit/debit can be done manually via the admin

Claim workflow 2:

    As above with the exception where more than one participant can claim a sale (more than one could be 5 or 10 unless this needs to be capped)
    A sales claim once loaded will expire in 14 days (we could configure an expiry policy in the admin for this)
    Each participant who claims a sale will be awarded the same number of points (points are not split)

**Comment by bradmac** [comment]
Need to support 2 use cases. The one above, and also this:
https://kademi.atlassian.net/browse/MC-3

Basically
- individual claims submitted together in a claim group
- must support for contact form fields and profile creation workflow
- optional validation of claims against existing records
- proof of purchase can be captured on the claim group instead of each sale item
- extra fields, eg for bank account info
- consider how to handle multiple parties, eg a supplier and an installer

**Comment by bradmac** [comment]
@mrdadah and @mkhoudary over to you
