### ISSUE TITLE
Claim nodes are broken

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5268]
http://blackberry-demo.admin.kademi.us/funnels/claim-journey/version1/#journeyBuilder-tab

They are not linking.

![image](https://user-images.githubusercontent.com/2201340/38158871-6c299b86-34e8-11e8-8366-b8a3c051acf2.png)

Notes;
The first email is delivered  but does not render in the email client.  Note if you test send it, it does render.
http://blackberry-demo.admin.kademi.us/manageUsers/21359265/#emailAppTab-tab

The 2nd email after the claim approved node does not get sent.

**Comment by bradmac** [comment]
I can see 2 journeys created for this user:
http://blackberry-demo.admin.kademi.us/manageUsers/21359265/#funnelsTab-tab

Both have proceeded past the sales claim goals, so the link problem above is just cosmetic, it has no functional impact.

![image](https://user-images.githubusercontent.com/826458/38169588-27f940a8-35c2-11e8-9942-c65f7afd5749.png)

**Comment by bradmac** [comment]
The problem with blank email content was because the sendemail nodes didnt have a contentFileName property.

This gets set when you save the email properties on the journey. I'm not sure why it didnt get set, but just saving corrected the problem.

And i've added a check to the send email goal so that when an email is being generated if there's no content file name we default to the standard.
