### ISSUE TITLE
Count down timer component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5436]
Please create a count down timer component. This should allow configuration of a date which is being counted down to, and use an appropriate jquery library to produce the count down, eg
https://hilios.github.io/jQuery.countdown/

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/40036606-ace9a892-5832-11e8-9b6a-01132581e132.png)

**Comment by Uafinder** [comment]
Ok,
First of all it counts 2 seconds instead of 1...
59-57-55-53 (one step takes 1 seconds but counts 2 seconds)

Then headers for each hour, mins and secs are off from container a bit
![image](https://user-images.githubusercontent.com/1945230/40059657-4cbdf006-585d-11e8-88cb-2736d6f8bb6a.png)
http://vladtest51kaucstore-vladtest51k.kademi-ci.co/page1.html

When minutes counter is selected then twin dot should be removed
![image](https://user-images.githubusercontent.com/1945230/40059736-8d85fb74-585d-11e8-9d7e-02cc5ec9a703.png)
http://vladtest51kaucstore-vladtest51k.kademi-ci.co/page1.html

Component is not scalable... it hardly fit to 50 * 50 container
![image](https://user-images.githubusercontent.com/1945230/40059843-d6e2671c-585d-11e8-8f8b-0e03171b38c7.png)
http://vladtest51kaucstore-vladtest51k.kademi-ci.co/page1.html

**Comment by bradmac** [comment]
i think this is fine
