### ISSUE TITLE
Kcom2: install to a website doesn't enable app in website apps

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5523]
http://vladtest52h.admin.kademi-ci.co/websites/vladtest52hweb/version1/#panel_apps-tab

**Comment by bradmac** [comment]
KCommerce2 is enabled:
![image](https://user-images.githubusercontent.com/826458/41009198-938aef98-6983-11e8-96d6-572165ddb95f.png)

**Comment by bradmac** [comment]
@Uafinder can you please confirm what problem you're seeing?

**Comment by Uafinder** [comment]
Confirm that problem persists...
![image](https://user-images.githubusercontent.com/1945230/41104463-11eab3a0-6a74-11e8-95db-8abcd06d7287.png)
http://vladtest52k.admin.kademi-ci.co/websites/vladtest52kweb/version1/#panel_apps-tab

**Comment by bradmac** [comment]
This is correct, the "ECommerce" app definitely must not be installed in a website using KCommerce2 because they will conflict.

Note that KCommerce2 is a standlone app, it does not depend on ecommerce-lib or the ECommerce app.

However, the ECommerce app is required in the admin for management screens.

**Comment by Uafinder** [comment]
Yup, thanks
