### ISSUE TITLE
Error while opening some pages, keditor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5591]
![image](https://user-images.githubusercontent.com/1945230/41808334-8e182ef4-76e4-11e8-8dfb-cffde888cd16.png)
http://vladtest52v.admin.kademi-ci.co/pages/vladtest52vleads/version1/?contenteditor=index.html

I've tried to re-create fresh account but same appears there

**Comment by bradmac** [comment]
This was because the bootstrap-select-lib and fuelux-lib apps were not installed, but are needed by the leadman-lib app

See comment here - https://github.com/Kademi/kademi-dev/issues/5355#issuecomment-399790093

Please let me know if you can reproduce this in a fresh account, and if so what the steps are to reproduce it

**Comment by Uafinder** [comment]
Yup, looks fine now
I will keep an eye on it
