### ISSUE TITLE
Asset query / content type fields are not considered

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5595]
For Vayability, I wanted to use content type fields in asset query, trying to select any of these using expression builder returned blank selector.. checking ContentTypeFieldDefField, it showed that getType() and getOperators() returns NULL.

For test purpose I added return TYPE_STRING and in operators OPS_TEXT, UI worked and I can add the fields to the expression builder, but an exception came out of QueryBuilderExression, method buildQuery returned "Field XXX does not support queries" so at first I made ContentTypeFieldDefField implement ElasticSearchField, then removed the support and added code in buildQuery to ignore fields of type ContentTypeFieldDefField.

Since the current implementation of the AssetService is HibernateAssetService, the query is evaluated using Hibernate Criterias and not ES.

I'd like to discuss the approach you're thinking of to be able to use AssetQueries and use Content type fields in expression builder, the other solution is to bypass this and use regular ES queries and I don't want to do that.

**Comment by bradmac** [comment]
> Since the current implementation of the AssetService is HibernateAssetService, the query is evaluated using Hibernate Criterias and not ES.

@mkhoudary we cannot use HibernateAssetService for this type of query because the values are stored in a single text field which holds them as XML

> so at first I made ContentTypeFieldDefField implement ElasticSearchField

ElasticQueryField extends Field, which is used for KCode templating, and is also integrated into Dynamic groups (see GroupManager 649 for an example)

ContentTypeFieldDefField extends Field so that content type fields can be used with KCode

It would only be beneficial for this to extend ElasticSearchField if it was to be used in dynamic groups, since thats the only thing that uses ElasticSearchField

But that is not appropriate here. Note that the content query builder is querying based on information about the user. Eg we want rules which say one type of user sees certain information (because a rule based on the user matches) and some other type of user will see other information.

This query framework is not intended to query information about the content, and i dont see how it could.

So what i think you should be doing is creating rules for each type of user, and each of those rules selects appropriate content.

![image](https://user-images.githubusercontent.com/826458/41824556-1f352d9c-7866-11e8-969e-9385f7de3b3b.png)

**Comment by mkhoudary** [comment]
This is clear now..
