### ISSUE TITLE
EDM content and metadata in sending emails (journey node)

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5613]
When using Send Email node in JB, we need to be able to let the node utilize assets in metadata and content.
Since we can work around that by using asset query component in email content, we need to have a more elegant solution for the whole email.

**Comment by mkhoudary** [comment]
@bradmac I would suggest a core asset type called EDM, that contains the exact fields of an EDM.. and in the node we can select either regular way (manual fields with MVEL and stuff) or asset query way, where we query an EDM asset type which contains metadata and content.

**Comment by bradmac** [comment]
How about this for a possibility:

- user selects an asset query for the email as a whole
- we use the query target content type to get a list of available fields
- the user can then select those fields for each metadata property on the email, eg subject, from, reply-to

We would want to consider the UX carefully because we want to retain a simply UI for the normal situation of entering those fields directly. So some sort of option which if chosen reveals the asset UI

**Comment by mkhoudary** [comment]
Proposed is to have a combo with metadata source:
![image](https://user-images.githubusercontent.com/3704174/42270119-b8588766-7f88-11e8-9599-febcef798aee.png)

When selecting manual nothing will change .. same will be showing.

When selecting asset query the following will show:
![image](https://user-images.githubusercontent.com/3704174/42270332-3d4a135e-7f89-11e8-9f01-8fa58bd0e280.png)

Please confirm so I can proceed.

**Comment by bradmac** [comment]
I think it will be quite common that they wont want to use a contenttype field for some things. Eg the user might just want to use it for subject, but not from, to or reply-to.

So the user needs to be able to either select or type a value in. We want a compact UI for this otherwise the page will be huge, something like this might be ok
![image](https://user-images.githubusercontent.com/826458/42271798-4ef5a574-7fd8-11e8-9373-3afc8889b5da.png)

**Comment by mkhoudary** [comment]
Agreed

**Comment by mkhoudary** [comment]
Done..

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-vaya-vayability/issues/75

**Comment by bradmac** [comment]
@mkhoudary i've made a few changes
- switched to looking up field values from AssetManager instead of using resources (more efficient, less brittle)
- refactored the send logic so it can be called from the test function
- integrated value lookup with translations so now metadata fields can come from translated versions of content assets

**Comment by Uafinder** [comment]
I've followed your instructions but was not success to receive email with translated subject
content type
http://vladtest53d.admin.kademi-ci.co/content-types/EmailMetaData/
content item with translations and query here
http://vladtest53d.admin.kademi-ci.co/asset-manager/
journey here
http://vladtest53d.admin.kademi-ci.co/funnels/first-journey/version1/#journeyBuilder-tab
Emails which i tried to send - here
http://vladtest53d.admin.kademi-ci.co/emails/?q=&status=&job=

**Comment by bradmac** [comment]
OK, its because the translation is being driven by the profile of the logged in user, rather then the recipient

**Comment by bradmac** [comment]
I've put in a fix to set the current user when generating the email. Need to check it.

**Comment by bradmac** [comment]
Seems to be working

**Comment by Uafinder** [comment]
i think that From field is using one translated text instead of being language sensitive
here is profile, no language selected
http://vladtest53f.admin.kademi-ci.co/manageUsers/17069329/#summary-tab
this is a default content item
http://vladtest53f.admin.kademi-ci.co/asset-manager/b999709a-c3c8-4d6d-ad21-3c37063faadd
And this is a resultant email
http://vladtest53f.admin.kademi-ci.co/emails/17080255

![image](https://user-images.githubusercontent.com/1945230/42825412-a1dece48-89ea-11e8-8e10-294f94bb4d8a.png)

**Comment by bradmac** [comment]
@Uafinder i moved that last comment to a new issue. If there's no show stoppers this issue can be closed

**Comment by Uafinder** [comment]
Ok, closing it.
just reopened it, to avoid long story...
