### ISSUE TITLE
User Management Issues

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#5738]
Found some issues with the User Management (under Users & Groups)

Feel free to use: http://asrdev.admin.kademi.us/manageUsers/ to test these. It's not a live site.

**1) What's the difference between removing a user and disabling a user?**

Removing this way (Type A):
![image6](https://user-images.githubusercontent.com/7914822/43104548-d4e1b3aa-8e9f-11e8-88b7-dc18938eeca7.png)

Doesn't yield the same results as this (Type B):
![image8](https://user-images.githubusercontent.com/7914822/43104642-1eb2af0c-8ea0-11e8-83a3-b747e742c1b5.png)

Type A - Removes the user's connection to points, groups, extra fields, etc. I say connection, because all their point transactions are still there, but can no longer see in the user's profile information.

Type B - The user still has connection to all their information, just disables the user. (This would be the preferred way both would work).

**2) Can no longer re-enable a user.**

I get the following error when I try to re-enable a user. The users I am trying to re-enable, are people that I just disabled.

![image2](https://user-images.githubusercontent.com/7914822/43104905-fa728a4e-8ea0-11e8-8eb9-31aa6f32d172.png)

**Comment by Uafinder** [comment]
Hey!
1. When you disable user - it will save all user information, but prevents it to login. This is userful for temporary restriction.
2. When you delete user - it will remove all information about this user, regarding points, data, learning and so on. It's intended not to delete points itself because usually points are legal even after user deletion. Same with sales data info.
Both cases user could be re-enabled.
error you saw is caused by some old record in database, which has same username field that's why it could enable it back. it shouldn't be reproducible in real life when every userid is unique
you could perform a clean test, create a new user and then disable him
also, in your case you could change userid and it also will work
![image](https://user-images.githubusercontent.com/1945230/43130502-809f3484-8f3f-11e8-8062-0f070270f4f3.png)
![image](https://user-images.githubusercontent.com/1945230/43130511-862ed56c-8f3f-11e8-9cb5-f9eec0767c5e.png)
![image](https://user-images.githubusercontent.com/1945230/43130522-8bbcb95e-8f3f-11e8-85aa-4e5258182092.png)

**Comment by bradmac** [comment]
:+1: 

Just to confirm about the userid thing, if you delete (is disable) a profile Kademi will allow you to create a new profile with the same userid. But if you try to re-enable that again that will not be allowed, because that would result in 2 actve users with the same userid. Vlad's suggestion above is correct, just change one of the userids
