### ISSUE TITLE
Content Type: No way for a field type to link to a dropdown, option list etc.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#5786]
Would be nice when extending additional Product Attributes to be able to link to predetermined set of options, which front-end dev can decide to make dropdown, checkbox, or text.

Example: ingredients list, "ideal for" list.

The key here is to have a predetermined set of options that can be selected per product. Choose one or more from a predetermined list.

At the moment I have to use a text field option.

**Comment by bradmac** [comment]
Updated XML structure:
```
<contentType>
  <name>Pet</name>
  <abstractType>false</abstractType>
  <fields>
    <typedField>
      <name>petName</name>
      <indexed>true</indexed>
      <text>petName</text>
      <title>Pet name</title>
      <options>
        <entry>
          <string>red</string>
          <string>Red</string>
        </entry>
        <entry>
          <string>dark-red</string>
          <string>Dark red</string>
        </entry>
      </options>
      <required>true</required>
    </typedField>
  </fields>
</contentType>
```

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/43618372-e6900a8c-971b-11e8-9c76-aeb751a9524b.png)

**Comment by bradmac** [comment]
Add options as comma seperated values:
![image](https://user-images.githubusercontent.com/826458/43618487-c3ddd3c4-971c-11e8-9d4d-91866e950417.png)

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/46953980-fbec3300-d097-11e8-824c-223c5a3113a0.png)
http://vladtest54c.admin.kademi-ci.co/asset-manager/9f5bfd74-ee4e-4497-9c5a-adb3305996d5
![image](https://user-images.githubusercontent.com/1945230/46953998-0a3a4f00-d098-11e8-9e35-7a9e1d8df7e4.png)
http://vladtest54cweb-vladtest54c.kademi-ci.co/dashboard

![image](https://user-images.githubusercontent.com/1945230/46954024-1b835b80-d098-11e8-8d37-0d84d886eabc.png)
http://vladtest54c.admin.kademi-ci.co/content-types/ActivityDefinition/Engine111

It seems display index instead of value

**Comment by Uafinder** [comment]
Ok, so looks fine
