### ISSUE TITLE
KCRM: New leadman dashboard components

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5842]
![image](https://user-images.githubusercontent.com/826458/44313842-7ff0b880-a463-11e8-8867-0092e8df4ec3.png)

https://preview.uxpin.com/e3a2a9f91e732e9b83bd8a8767f8d3f5785da182#/pages/87029710/simulate/sitemap?mode=i

**Comment by anhnt** [comment]
this is done 
- leadsList component for leads
- leadDashTasks for tasks

![image](https://user-images.githubusercontent.com/735555/44519063-1dfbb180-a6f6-11e8-9297-2762afb6c21c.png)

**Comment by anhnt** [comment]
i need to create thumb images and settings for them

**Comment by Uafinder** [comment]
Did you put them to dashboard by default? Or not yet?

**Comment by anhnt** [comment]
@Uafinder those components will not be put on dashboard by default.

**Comment by Uafinder** [comment]
keditor adding component:
Code appears
![image](https://user-images.githubusercontent.com/1945230/44729643-ea4ecc00-aae7-11e8-86b9-61f37040b7b5.png)

i'm not seeing incoming task component
![image](https://user-images.githubusercontent.com/1945230/44729731-19653d80-aae8-11e8-80f2-923a479cc955.png)
http://vladtest53t.admin.kademi-ci.co/websites/vladtest53tweb/version1?editTemplate=theme/apps/user/dashboard

**Comment by bradmac** [comment]
Guys, not needed for GH, so please ignore this issue for now

**Comment by bradmac** [comment]
Pushed back to milestone p1

**Comment by anhnt** [comment]
>send email button gives you email message with correct email recipient and BCC to some weird address

This is for leadman app to track the email and actions

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/46275833-7a20e380-c588-11e8-9f41-c3cfa6878d35.png)

>i'm not seeing incoming task component

This is available via settings named Unassigned tasks

**Comment by anhnt** [comment]
Other problems are sorted

**Comment by Uafinder** [comment]
1. Open settings for task board cause nothing selected
![image](https://user-images.githubusercontent.com/1945230/46569821-31d83b80-c963-11e8-801a-c0fbc78095de.png)
http://vladtest53z.admin.kademi-ci.co/websites/vladtest53zweb/version1?editTemplate=theme/apps/user/dashboard
Should be some value by default

2. Send email issue still active
![image](https://user-images.githubusercontent.com/1945230/46569833-795ec780-c963-11e8-9708-513dac3c4e0a.png)
http://vladtest53zweb-vladtest53z.kademi-ci.co/dashboard

3. Tasks not appear in list after using create task button - refresh needed
![image](https://user-images.githubusercontent.com/1945230/46569855-d9ee0480-c963-11e8-8b20-794dc111a59f.png)
http://vladtest53zweb-vladtest53z.kademi-ci.co/dashboard

4. Take this task button should delete task from one component and add it to another (move fron unassigned to due to)
![image](https://user-images.githubusercontent.com/1945230/46569882-52ed5c00-c964-11e8-9662-4483268f2941.png)
it wasn't happen

**Comment by anhnt** [comment]
1 - fixed
2 - this is intended to track the lead with emaik
3, 4 - looks good to me

**Comment by Uafinder** [comment]
ok, looks good
