### ISSUE TITLE
Points tab on profile page now showing content

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5873]
http://mhiaainstaller.admin.kademi.com.au/manageUsers/126254198/#summary-tab

The page is blank

**Comment by bradmac** [comment]
Thats because the user is not connected to any org with points

The points bucket is configured for orgs of type "account holder"
![image](https://user-images.githubusercontent.com/826458/44513061-7c358e00-a710-11e8-975e-03308bf95b91.png)

But the user's org is not of that type:

![image](https://user-images.githubusercontent.com/826458/44512936-252fb900-a710-11e8-88d1-835947339599.png)
