### ISSUE TITLE
Email buttons not rendering with correct style

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5928]
http://mhiaainstaller.admin.kademi.com.au/groupEmails/126155207/#messages-tab

Correct rendering 

![image](https://user-images.githubusercontent.com/2201340/45126866-df1b3080-b1b8-11e8-8f6e-42a5aaa1bebb.png)

Incorrect rendering affects
Detail view for Outlook 2007 (Win 7
Detail view for Outlook 2010 (Win 7)
Detail view for Outlook 2013 (Win 7) 
Detail view for Outlook 2013 120 DPI (Win 7) 
Detail view for Outlook 2016 (Win 7) 
Detail view for Windows 10 Mail (Win 10) 
Detail view for Gmail App (Android 6.0) 
Detail view for AOL Mail (Explorer) 
Detail view for New Gmail (Chrome) 
Detail view for Inbox by Gmail (Chrome) 
Detail view for Inbox by Gmail (Firefox) 
And more.....

![image](https://user-images.githubusercontent.com/2201340/45126881-f0643d00-b1b8-11e8-9b98-d048ef9a73ba.png)

**Comment by bradmac** [comment]
Looking at the html..

```
<a title="Confirm Registration" href="http://mhiaapowerplus.com/do-reset/?token=8d6ec160-2655-4918-920b-9df7c4399691" target="_blank" style="font-size: ${buttonFontSize}px; font-weight: bold;  text-align: center;  text-decoration: none; color: #ffffff; font-family: arial,helvetica,sans-serif; font-style: ">Confirm Registration</a>
```

The problem is most likely because buttonFontSize is coming out as a template variable, and thats invalid syntax which can cause styles to be ignored.

All EDM components need to ensure they do not output template code like this in any circumstances because its a strong spam indicator.

To resolve this you can probably just set a value for the button font size, but it should have a sensible default

**Comment by bradmac** [comment]
@anhnt please check the button component and make sure template code is never ever ever output for any reason. ever.

**Comment by anhnt** [comment]
Fixed

**Comment by anhnt** [comment]
Note that this is Password reset button, not common button

**Comment by Uafinder** [comment]
Looks good
