### ISSUE TITLE
KCRM: Adding several groups to a team member

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5940]
![image](https://user-images.githubusercontent.com/1945230/45208659-caf83180-b293-11e8-8ed0-2f6d3b3f3f4a.png)
http://vladtest53uuweb-vladtest53uu.kademi-ci.co/team/
When adding new member and assign several groups it gives you error

**Comment by bradmac** [comment]
The server is expecting a single group.

I dont think its a good idea to allow multiple selections, it doesnt make sense to create a user as both a "sales manager" and a sales staff member - that will be confusing.

@anhnt please update group selection to be radion buttons instead of checkboxes. And apply same for SP.

**Comment by anhnt** [comment]
Applied to SP

**Comment by Uafinder** [comment]
it works on CI
