### ISSUE TITLE
kcom2 - first shipping address fields not saved, nor copied to payment process "tab"

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6012]
Once logged in on a new browser, checkout step 2 asks for shipping address details. Once these are entered, step 3 asks for shipping cost. Once shipping cost is completed, step 4 is payment gateway.

The issue is that it asks for shipping address again, even though I have filled this in already in step 2, on a stand-alone shipping address step. (used to calculate shipping no doubt).

Also, this shipping address is not saved anywhere, once I post it. Possibly only saved to cookies or session, but not against profile.

site: http://plantae-plantae.kademi.com.au

**Comment by bradmac** [comment]
Currently the standard kcom2 checkout process does not allow selection of an existing profile address:
![image](https://user-images.githubusercontent.com/826458/45946116-fde84680-c043-11e8-8913-4ad4b0085b0c.png)

> The issue is that it asks for shipping address again, even though I have filled this in already in step 2, on a stand-alone shipping address step.

The address entered in payment details is not a "shipping address", its part of credit card verification and will often be different to the shipping address, so we cant just re-use the shipping address for payment verirfication.

Kademi does not store any part of payment details anywhere, which is essential because we're leveraging PCI compliance of payment platforms.

However i think it does make sense to pre-populate payment address fields from the provided address

**Comment by bradmac** [comment]
update our standard eway payment form to pre-populate address fields from the current cart billing address, or shipping address (if there is no billing address)

**Comment by stephen-fueldesign** [comment]
I agree.

1. Store shipping address against profile (_else what's the point of logging in, from user's perspective_)
2. Pre-populate credit card address details with shipping address is a welcomed feature.

**Brad, here's a proposal**.
Just like there is a checkbox for billing address same as shipping, you could prompt on the credit card payment page "CC address same as shipping address" and "billing same as CC address".
Something along those lines.

What this means is that potentially returning customers could add items to cart, checkout, login and boom all address fields potentially be pre-populated.

1. login
2. choose shipping costs
3. enter credit card details.
4. boom!

Step 4 is optional.

**Comment by bradmac** [comment]
I think the CC address fields need to be shown anyway, so rather then adding a checkbox simply pre-populating them anyway might be a little simpler. If the address is the same the user doesnt need to do anything. If its not the same well they need to type it in anyway.

**Comment by anhnt** [comment]
Done, please update to use latest eway-lib and kcom2 app

**Comment by Uafinder** [comment]
Ok, it works
But with issues
https://github.com/Kademi/kademi-dev/issues/6136
And sometimes it's not prepopulated at all. Cure is hard refresh.

**Comment by bradmac** [comment]
#6136 is closed ... so should this issue be closed @Uafinder ?

**Comment by Uafinder** [comment]
Yes, looks good
