### ISSUE TITLE
Table Uploaders

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#6026]
A couple items with the Table Uploaders:

- Sometimes when uploading through the Points Uploader, the process skips past the Options tab without giving time to select the specific options. I don't know if this only happens with the Points Uploader or if this happens with other uploaders as well and I don't exactly know what is causing it -- I wasn't able to replicate it in any of my testing today. This happens in both Firefox and Chrome browsers. Don't know if it is an issue in Internet Explorer.
- On the "Review Page", disable Next until Import is clicked
- On the "Processing Page", disable Next until Processing is complete

**Comment by bradmac** [comment]
@Uafinder please review the comments above, and identify any changes required

**Comment by Uafinder** [comment]
1. It's a well known issue, appears when you use one uploader multiple times... marked as a low priority
2. Disable Next button on review page not needed, there is a validation persists
3. Disable Next button on Processing page is possible, but not needed at this moment because if you push next, you will see summary and will go back momentarily to the processing page.
So no specific changes needed at the moment i think.

**Comment by bradmac** [comment]
@faithtek that sound ok?
