### ISSUE TITLE
KCom2: browse by category is clickable

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6141]
Browse by category section should be not clickable, but selectable
![image](https://user-images.githubusercontent.com/1945230/46870657-d9f47580-ce37-11e8-9c5b-30a41bbe7baa.png)
http://vladtest54bweb-vladtest54b.kademi-ci.co/vladtest54bweb-ecomstore/

Also, when you land on the some specific category page, browse by category section should be hided
http://vladtest54bweb-vladtest54b.kademi-ci.co/vladtest54bweb-ecomstore/Electronics/

**Comment by bradmac** [comment]
> Browse by category section should be not clickable, but selectable

I think the intention is that we do click through to the category page, and thats because often a category will have additional content, eg promotions and descriptive text about the range of products

So that means its "clickable", not just "selectable"

> Also, when you land on the some specific category page, browse by category section should be hided

Thats not necessarily true. In some stores they will want to show the category list, and others not.

Users can edit the appropriate templates to achieve the layout they want

**Comment by Uafinder** [comment]
ok, got it
