### ISSUE TITLE
Free gift with purchase promotions with kcommerce2

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6208]

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/47688776-cfb1e400-dc4b-11e8-8b43-0c967e2fbd33.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/47688814-f6701a80-dc4b-11e8-964e-4791585516a2.png)

**Comment by Uafinder** [comment]
This user
http://vladtest54ss.admin.kademi-ci.co/manageUsers/18183444

Purchase this
http://vladtest54ssweb-vladtest54ss.kademi-ci.co/vladtest54ssweb-ecomstore/fitbit000

![image](https://user-images.githubusercontent.com/1945230/48411245-aca62a80-e749-11e8-9c3a-25a88e4da67f.png)

note that 2 racing car promos appears instead of one

**Comment by bradmac** [comment]
ha ha, oops. When copy/paste goes wrong.

Fixed.

**Comment by Uafinder** [comment]
ok, looks good
