### ISSUE TITLE
Assets keditor missed image component

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6240]
http://vladtest54mm.admin.kademi-ci.co/asset-manager/0f7d4761-8dd8-412b-89e2-f3ccbd27415d
![image](https://user-images.githubusercontent.com/1945230/48122895-5769a500-e281-11e8-8c96-4bc85aefb33b.png)
![image](https://user-images.githubusercontent.com/1945230/48122874-50429700-e281-11e8-8db4-873fb844974f.png)
When using build in product asset keditor - there photo component missed

**Comment by bradmac** [comment]
Note that as that field is a EDM field, it should have the EDM photo component

![image](https://user-images.githubusercontent.com/826458/48123182-279cba80-e2de-11e8-82ea-4d93aa0168cc.png)

**Comment by bradmac** [comment]
I updated libs (account level), and is working now

![image](https://user-images.githubusercontent.com/826458/48321451-6dafa080-e687-11e8-951a-d301fe169d30.png)

**Comment by Uafinder** [comment]
i've created a fresh account and tried again, but have no luch to found photo component
http://vladtest54r.admin.kademi-ci.co/asset-manager/b9bc7ca3-3c6a-448a-8ac2-415fca91c9f3
Access this page and push + icon near content field
![image](https://user-images.githubusercontent.com/1945230/48343108-31c20e80-e67a-11e8-80c5-23f05cc13d4b.png)

**Comment by bradmac** [comment]
OK, there is a second problem. When an asset is edited from another asset (ie when clicking the pencil icon), the components are being loaded for the first asset. Since that is a contentitem, not text asset, many components are not available.

![image](https://user-images.githubusercontent.com/826458/48372425-6b9b1f80-e723-11e8-8480-0d5edc4279e6.png)

![image](https://user-images.githubusercontent.com/826458/48372444-7fdf1c80-e723-11e8-8200-c09eaca9c105.png)


But if you open the related asset in a new window you can see components are loaded correctly

![image](https://user-images.githubusercontent.com/826458/48372467-8c637500-e723-11e8-8872-5d30c0fe943e.png)

**Comment by bradmac** [comment]
Fixed.

Requires admin-lib 1.3.9 /  content-lib 1.6.5

**Comment by Uafinder** [comment]
Same for me
![image](https://user-images.githubusercontent.com/1945230/52464653-6a438c80-2b84-11e9-817e-2d2e6df2cba7.png)
![image](https://user-images.githubusercontent.com/1945230/52464679-7fb8b680-2b84-11e9-8d3b-efd2412bcf0e.png)
Fresh account
http://vladtest56mmm.admin.kademi-ci.co/asset-manager/new?type=testcontent

**Comment by bradmac** [comment]
@Uafinder please confirm this is working for existing assets.

It looks like there is a problem when creating a new asset, but that should be treated as a seperate issue with a lower priority because there is a simple workaround.

**Comment by Uafinder** [comment]
Yes, it works when create asset and then open it for edition separately.
