### ISSUE TITLE
Sales-manager member can't create team

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6260]
Is this correct?
http://vladtest54r.admin.kademi-ci.co/manageUsers/18078922/#summary-tab
![image](https://user-images.githubusercontent.com/1945230/48344637-4ef8dc00-e67e-11e8-8046-b88299d9eab5.png)

**Comment by bradmac** [comment]
That group only has user admin role within their own team/organisation:
![image](https://user-images.githubusercontent.com/826458/48372773-88842280-e724-11e8-931d-82f8184be616.png)

So that role does not give them permission to create new teams.

To be able to create new teams they need user admin permission on the account

**Comment by bradmac** [comment]
BTW, just to be clear .. there is nothing special about any group. Its only the roles on the group that matter.

**Comment by Uafinder** [comment]
Ok
