### ISSUE TITLE
Asset Manager not correctly filtering by type (on custom types)

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6313]
Seems to work with the built-in types such as : "query, image, video, text, public. even category and product" but not on the custom type on waterware.

https://waterware.admin.kademi.com.au/asset-manager/

**Comment by bradmac** [comment]
fyi, here's what i see in the logs..
```
search query=[] inc types=[productoverview] ex types=[]
```

Note the hyphen is missing

**Comment by bradmac** [comment]
OK, i think this is because of a bug that was introduced and fixed (but not deployed) last week.

Will be fixed in next deploy which should be later today

Note that it only applies to content types with a hyphen in the name. I recommend not using that pattern, and instead using camel case .. eg ProductOverview. That can then be used directly in templating code without quotes.

**Comment by bradmac** [comment]
problem is still active after deploy

**Comment by bradmac** [comment]
Deploy wasnt done correctly. Done now and problem is resolved.
