### ISSUE TITLE
KCRM: Details section UX improvements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6321]
1. the edit button should apply to the whole detail form, not just description. Move to top right, or lower right.
2. links in description should be clickable (same as for comments)
3. newlines should be preserved
4. should be able to paste images (same as for comments)

![image](https://user-images.githubusercontent.com/826458/49039256-23e8bd80-f224-11e8-8575-0f09172489b3.png)

**Comment by anhnt** [comment]
Done in v3.2.5

**Comment by Uafinder** [comment]
When you click edit, custom fields disappear
![image](https://user-images.githubusercontent.com/1945230/49155381-78bf2d80-f323-11e8-928d-f16115497574.png)
![image](https://user-images.githubusercontent.com/1945230/49155390-7eb50e80-f323-11e8-9f53-10e2c71daf01.png)
http://vladtest54yweb-vladtest54y.kademi-ci.co/leads/18264296/

Would be great to have something like "DONE" button
http://vladtest54yweb-vladtest54y.kademi-ci.co/leads/18264296/
![image](https://user-images.githubusercontent.com/1945230/49155509-cc317b80-f323-11e8-9025-a7e8b747f6dc.png)

When you upload image via drag and drop you should click outside the field area to save changes
Otherwise it  will not save changes
Also there could be such bug
![image](https://user-images.githubusercontent.com/1945230/49156577-5a0e6600-f326-11e8-97d5-a38f8954a3be.png)
When it save text for uploading instead of image itself

**Comment by bradmac** [comment]
> Would be great to have something like "DONE" button

I agree. It doesnt make sense to save on change in a situation like this,.

Should be just the same as github issues.

**Comment by bradmac** [comment]
@anhnt can you change that to "Save" to be consistent with other forms in kademi? Also, i think we normally use the success style..

![image](https://user-images.githubusercontent.com/826458/49197805-2fd7a980-f3f5-11e8-9592-08a26fb303b5.png)

**Comment by anhnt** [comment]
@bradmac this page is saving any thing automatically after you changed. Do you mean we remove that feature and use a save button to submit form?

**Comment by bradmac** [comment]
Yep. It doesnt make sense to have auto-save when the user clicks a button to show the edit form.

This should be the same as github issues. Click a button to switch to edit view, then click another button to save.

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Doesn't work
nothing is saved
![image](https://user-images.githubusercontent.com/1945230/49220860-04968f80-f3e0-11e8-889c-328afa5ec68d.png)
![image](https://user-images.githubusercontent.com/1945230/49220872-0c563400-f3e0-11e8-98a7-c4c925af77b0.png)
http://vladtest54zweb-vladtest54z.kademi-ci.co/leads/18267473/?view=detail
Fresh account

**Comment by bradmac** [comment]
> Doesn't work nothing is saved

Fixed. @anhnt I merged the controller methods for updating details and handling assigned to.

**Comment by Uafinder** [comment]
It works
