### ISSUE TITLE
Shopping Cart Issues

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#6422]
Some change made earlier today by the team, broke the shopping cart + - buttons.

This is now what they look like in all my sites (even those without many reward store modifications):

![image1](https://user-images.githubusercontent.com/7914822/49905072-5ad0ed00-fe3a-11e8-9a20-65c0dd7afff7.png)

Please look at this. You can use http://main-asrge.kademi.us/primary/ if you need to test.

Michael

**Comment by bradmac** [comment]
@faithtek looking at the repo history, i can see libs were updated about 20mins ago, which included changing the bootstrap-base and k-theme lib versions

So the problems you're seeing might be because of that.

i suggest you just revert to that previous commit:
http://asrge.admin.kademi.us/repositories/main/commit-65108790/

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/49905728-c024ec80-fed3-11e8-9f45-1b9c85c0058d.png)


![image](https://user-images.githubusercontent.com/826458/49905741-c915be00-fed3-11e8-8c90-1a0b1c315268.png)

**Comment by faithtek** [comment]
Thanks.
