### ISSUE TITLE
EDM asset image issue when image is large

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6523]
![image](https://user-images.githubusercontent.com/1945230/50968529-0a55b980-14e4-11e9-97b4-6e541bda14e1.png)
http://vladtest55xx.admin.kademi-ci.co/asset-manager/834a047a-2046-40a8-8fe9-fabfef1cd218

To reproduce
- Create new edm asset
- add some container and add there some photo component with some image
- save
- close
- then try to open it for edition

**Comment by anhnt** [comment]
cant reproduce locally. also i cant reproduce on your test account after updating all libs

**Comment by anhnt** [comment]
this is pretty critical
but wont affect when user view on email client
and since we had used edm editor inside an iframe (like asset edm) it had occured 😃
this js that calculate the width of component was executed before css is loaded in iframe
so the width is full width of container, not the email wrapper usually 600px

**Comment by anhnt** [comment]
Fixed, requires keditor-lib 1.3.2

**Comment by Uafinder** [comment]
Looks good
