### ISSUE TITLE
Manager badges thoughts

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6550]
•	Sharing an update through activity feed
Storyteller: Once a month, Communicator = 3 times over journey, Announcer= one update
_i think we could do that, but do we have a possibility to react on sharing process?_

•	Participation in a manager group
_no need, because manager always has a manager group _

•	Liking/commenting on others’ activities within the wall 10 times
o	Wall participation with others, reinforcing interaction & awareness of other participant’s successes
_have no idea how to react on commenting_

•	Highest engagement with the participant they’re supporting
o	Dynamic Duo
o	Define engagement = posting to walls, tagging in posts, like or comments within feed, nominating for badges
o	Monthly basis out of ALL manager-participant duos within cohort—1 badge per month 
o	Issues if there is a manager that has more than one participant they’re supporting?
o	Can participants view manager’s badge collection?
_i think this one is very complicated conditions, we could provide a per month badge, and for example badge for managing more that one participant_

**Comment by bradmac** [comment]
> Sharing an update through activity feed - i think we could do that, but do we have a possibility to react on sharing process?

@tuzzmaniandevil i think postting a file to a wall is just a normal wall post, right? ie uses ForumManager.newWallSharedItem .. ?

If so i think we can fire an event from there and use that to trigger a goal.

> Liking/commenting on others’ activities within the wall 10 times

"commenting" : This is also a wall post so could use the same as above

I think we would want this new goal to have a couple of parameters
- type: eg file share, comment
- count: number of times the user has submitted this type of post

Note that to ensure good performance, i think the goal should save itself and parameters somewhere, and the funnel manager would check that instead of scanning all funnels

> "liking"

this is different to a wall post, this uses votes. So i think we could add a new goal for Voting, both for placing votes and receiving them. As above should have a parameter for the number of that type, and should be saved to a relational list for performance to avodi scanning funnels

>  Highest engagement with the participant they’re supporting ... Define engagement ... etc

Yeah, i think this is poorly thought out. Badges should be awarded for specific, easily understood actions. Not arbitrary combinations of actions.

I think instead of a badge they should use levels. This would apply gamification techniques where managers receive XP points for various actions (which will be saved as points in a points bucket) and they achieve levels as their XP moves up.

There would not be any monthly limit, but level jumps would get progressively larger. Eg 100 points to get level 1, but they need to earn 500 points to go from level 1 to level 2, etc.

To do this we need to define the actions which award XP points. Usually badges will award XP points, but also anything notable in their engagement, eg a participant who completes a challenge should contribute XP to the manager.

**Comment by bradmac** [comment]
Moved to https://github.com/Kademi/client-vaya-vayability/issues/439
