### ISSUE TITLE
Participants badges thoughts

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6551]
•	Addressing the frequency of logging in
o	Receive at end of month
o	Rockstar: 1 time a week per month, Superfan: 2-3 times a month, Achiever:1 time a month
o	Has the ability to collect multiple of the same badge
o	Future rollouts (group these into meta buckets ex: 3 rockstars = guru)
_would be great to have such node as "login goal" (found a user visit goal, is it suite?), if so we could do that_

•	Viewing 5 additional resources
o	What number would be best appropriate here, as the # of resources may vary per HT
o	Receive once the 5th is viewed
o	Over the course of the whole 6 month
o	Bookworm
_we have a paged view goal, but we specify there a specific page address, and i'm not sure if we can use it for that purpose_

•	Uploading 3 files to “My Files”
o	IDP, notes with FB sessions etc.
o	Over the course of 6 months
o	Data OR File Collector
_we have not such goal as file upload goal, so either we need to develop it, or we need to ignore that req_

•	Completing all activities requested for the month
o	= challenge, 2 surveys & reflection 
o	Recurring, get this badge every month 
o	The Wizard = everything, The Master= 2 activities, The Apprentice = 1 activity
_is it possible to reach it with decision node? i know that activities in Vaya is pretty custom_

•	Complete 90% activities requested throughout whole 6-month journey
o	Vayability Victory 
_i think we could do that via points counting, or we could use activities completion counter via decision node_

•	Reaching 1000 activity points
o	Roughly half the max amount of possible points to earn 
o	The Mountain Climber
_easily_

•	Participation in a group
o	Promoting teamwork within site
o	The Social Butterfly
_have no sense because participant always has a group_

•	When a participant has nominated 5 other people for badges
o	Team player/master recognition
o	The Cheerleader
_i think we have no possibility to nominate to badge and no word about in scope_

•	Adding a profile picture 
o	Easy win for someone daunted by task versus is this worth rewarding?
o	Say Cheese
_no such node and i don't think that it worth to be rewarded at all_

•	Utilizing the coaching call
o	Phone a Friend
_i think we could do that via page viewed goal or contact request goal_

•	Liking/commenting on others’ activities within the wall 10 times
o	Wall participation with others, reinforcing interaction & awareness of other participant’s successes
o	Over the course of 6 month journey
o	The Motivator
_have no idea how to react on commenting_

•	Sharing an update through activity feed 
o	Over the course of 6 month journey
o	Storyteller: Once a month, Communicator = 3 times over journey, Announcer= one update
_i think we could do that, but do we have a possibility to react on sharing process?_

•	Missing a habit and coming back to do things
o	The Comeback Kid
_i don't think we could track missing habit and complete expired activities_

•	Moving into a spot on the leaderboard
o	The Underdog
_not sure what that means_

•	Highest interaction = total activity points 
o	Squad Goals
o	On a monthly basis for whole journey
o	Reward group participation and involvement
o	Group badge**
_i think we need to focus on personal badges first, i don't think we could do that easily_

**Comment by bradmac** [comment]
> Has the ability to collect multiple of the same badge

Note this is specifically not allowed in kademi. This sounds like using levels, where participants gain XP from various actions including logging in, and as they "level up" as they progress, eg from Rock Star to Guru, etc.

> we have a paged view goal, but we specify there a specific page address, and i'm not sure if we can use it for that purpose

What is a resource in vaya? Is it a PDF etc? Or a web page? 

> we have not such goal as file upload goal, so either we need to develop it, or we need to ignore that req

yes we dont, and this sounds frivolous. It would be good to reward sharing files, but not uploading to their own folder.

>  Completing all activities requested for the month ... Recurring, get this badge every month

As above we do not support getting the same badge repeatedly. Instead we should recommend use of Levels. This should be combined with logging in to make a single XP based series of levels.

This way XP points can be awarded by the journey, or we can use the existing points system.

> i think we could do that via points counting, or we could use activities completion counter via decision node

Agreed, with points counting.

> Participation in a group - Promoting teamwork within site - The Social Butterfly

I think this would be a wall post goal (new goal) with a specified number of comments, eg 20. Would be across all types of posts, ie includes replies.

> i think we have no possibility to nominate to badge and no word about in scope

@Uafinder please flag this to vaya as not being specified in the solution design, and can be quoted on if required

> Adding a profile picture - no such node and i don't think that it worth to be rewarded at all

I think this would be valuable, because users profile pics does make the program more appealing (eg imagine facebook without faces). We would add a Profile Updated goal with options to specify if pic or other fields are set

> Utilizing the coaching call - Phone a Friend - i think we could do that via page viewed goal or contact request goal

Sounds good, @Uafinder can you check we do actually use the contact form for that?

> 	Liking/commenting on others’ activities within the wall 10 times

As above i think this is best used as contributing factor to XP, rather then as a badge itself. So each action would add a (small) amount of XP.

> Sharing an update through activity feed - Over the course of 6 month journey - Storyteller: Once a month - Communicator = 3 times over journey, Announcer= one update

As above, would use a new wall post goal. But again i see this as a series of levels, not badges.

**Comment by bradmac** [comment]
> Missing a habit and coming back to do things - The Comeback Kid

What does this mean? Do they mean not doing challenges for a while, and then doign one?

> • Moving into a spot on the leaderboard - The Underdog
> Not sure what that means

Same, not sure

**Comment by bradmac** [comment]
> • Highest interaction = total activity points

Again, i think this would be part of the overall XP levels series.

**Comment by bradmac** [comment]
Moved discussion to https://github.com/Kademi/client-vaya-vayability/issues/438
