### ISSUE TITLE
Image component missed edit feature in content type asset

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6682]
![image](https://user-images.githubusercontent.com/1945230/52466650-ad552e00-2b8b-11e9-8c7a-c8d5cb649bea.png)
http://vladtest56mmm.admin.kademi-ci.co/asset-manager/new?type=testcontent2

**Comment by bradmac** [comment]
hey @anhnt i think this is related to editing in a modal. So i suggest we change the UI here so we just edit related assets in a new window, instead of a full screen modal. It looks like this is too hard to get working reliably

So the + button for a asset relation field should just create the asset and then open the editor in a new tab

**Comment by bradmac** [comment]
Related - https://github.com/Kademi/kademi-dev/issues/6684#event-2126466319

and https://github.com/Kademi/kademi-dev/issues/6683

**Comment by bradmac** [comment]
Note that adding new assets is currently broken, eg

https://waterware.admin.kademi.com.au/asset-manager/97b80b5b-e419-4932-8484-acd3b130b728

**Comment by anhnt** [comment]
Fixed

**Comment by anhnt** [comment]
Requires content-lib 1.6.6

**Comment by Uafinder** [comment]
Fine now
