### ISSUE TITLE
New dashboard style with Tile concept

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#734]
We will have new style for dashboard with new concept named Tile (new for our dashboard). The specification of tile are:
 * Have 2 size: Medium and Large
 * Medium size is square
 * Large size has 2 kind: vertical and horizontal. 
 * Large-Vertical: has same width with medium but height is bigger than medium 2 times. 
 * Large-Horizontal: has same height with medium but width is bigger than medium 2 times.
 * Tile will have 2 types of animation: fade, slide (Up, Down, Left, Right) with 2 panes: preview (can be banner, logo or just plain text - name of tile) and detail with related information

**Comment by ducdhm** [comment]
@bradmac Please take a look at new style and feel free to comment about it. Thanks!

**Comment by bradmac** [comment]
@ducdhm that looks beautiful! But, i think we need a few changes..

- the idea of a dashboard is to see at a glance critical statistics. So we cant have panels that flip to show information, we need to see it initially.
 - the quick links are too big, we're going to have lots more of them and we need them to use space fairly efficiently. I think 100px high is about right.
 - the stream shows important events, and needs to be immediately visible above the fold. History is not that important, and we can swap history with stream. Recent posts can stay where it is.
- i think we should hide the breadcrumb div on the dashboard, that will free up vertical space
- the website panel (ie header and border) takes up unnecessary space, and i dont think it adds anything, people should know these are websites. So maybe remove the panel container.
- the large panels at the moment are using space really inefficiently. Eg the left half of the email panel is enormous to only convey a very simple piece of information. Remember we only have 3 stats panels now, but we will probably have 10 or more, and we want to achieve an appropriate information density so that users can see at a glance whats happening.

**Comment by bradmac** [comment]
@tuzzmaniandevil says layout doesnt work properly on Chrome

**Comment by paddyow** [comment]
A few comments from my end:
- I love the new panels, and although I do like the flip as it's brings life to page, I agree with Brads comment
- I feel like the App panels should click through to something relevant i.e. email could go to email history, memberships to groups etc
- Hide the minimize menu buttons for desktop, or just remove

I think the below is what everyone is after?

![example](https://cloud.githubusercontent.com/assets/2201340/9924397/6cddecb0-5d42-11e5-9a43-b3cb07cc0aa1.jpg)

**Comment by bradmac** [comment]
Yep, that looks right to me. One thing though, we will have more (and maybe less) of the quicklinks and stats panels. So that would push down the stats area. So would be good for the stream panel to match that height.
Agreed that the panels should click through to the home page for that thing, ie emails, signups, web access stats.

**Comment by ducdhm** [comment]
@bradmac I'll use js for make sure steam height always equals masonry panel

**Comment by ducdhm** [comment]
@bradmac Dashboard is done! Please kindly review it!

**Comment by bradmac** [comment]
Couple of changes
- please bring back the left menu collapse button, very important for tablets
- make the quick links wider, the text is too compressed in some resolutions
- dont worry about making quick link columns line up with stats panels!
- quicklinks should be in their own container, 
- quick link column classes should be specified in the markup not applied to everything in js. Thats to allow app developers control over variations
- large panels should be vertical, not horizontal. The horiztonal layout makes it not obvious that the 2 sections of a panel are connected.

**Comment by ducdhm** [comment]
Done!
