### ISSUE TITLE
Add a new Automation Action: Execute JavaScript

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#972]
This will allow an automation trigger to execute javascript code that can access application API or run custom app API.

**Comment by bradmac** [comment]
:+1:

**Comment by tuzzmaniandevil** [comment]
Oops. Closed by mistake

**Comment by tuzzmaniandevil** [comment]
Finally done :-)

**Comment by tuzzmaniandevil** [comment]
2 new columns though, on milestone

**Comment by bradmac** [comment]
@tuzzmaniandevil I can see some problems with the way thats done
- there is no way to utilise functions defined in external files
- a new engine is created each time which is slow

What might be a better option is this
- a website is selected as part of configuration of the event
- load the website js engine for the websiterootfolder, eg ContentApp.mappings(..)
- the event wont be in context, because the context is defined by ContentApp. So create  a local Bindings or ScriptContext which should include the engine context and extend it, and add the event to that, then call eval with that ... engine.eval(js, context)

**Comment by tuzzmaniandevil** [comment]
Done :-)
