### ISSUE TITLE
Ability to set login token expiry 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#986]
To be able to set the login token expiry to X days or have no expiry.

Should this be on an account where it is applicable to any login token, or at a website level?

This needs to be available for around the 7th December.  

Use case:  User clicks through from an email to a blog page with a video on it which displays their first name.  The user might want to go back to the email several weeks later and click on the link but not have the login token expire.

**Comment by tuzzmaniandevil** [comment]
The default expiry is 7 days, this can now be overriden form the Users app settings, on both website and organisation level, This will only override login tokens for websites, Organisations remain uneffected.
You can also choose to have a token never expire by using "none" in the settings instead of a value
